#!/usr/bin/env python3
"""Generates the schema-driven parts of the `opense4` Python package from the SDK's
docs, which are its schema (docs/sdk/view.md, docs/sdk/commands.md):

  python/opense4/enums.py       every enumeration, as a tuple of its names
  python/opense4/_records.py    a class for every type of the view, the rules view and
                                the commands, with a typed property per field
  python/opense4/cmd.py         a constructor for every command and every type a command carries
  python/opense4/order.py       a constructor for every order kind
  python/opense4/tactical.py    a constructor for every tactical order kind

Run it after changing those docs:

    python3 tools/gen_sdk_python.py           # writes the files
    python3 tools/gen_sdk_python.py --check   # exits 1 when a file is out of date

The SDK's tests run --check, and check what the constructors build against the
engine's command codec (tests/sdk/test_sdk_python.cpp).
"""

from __future__ import annotations

import argparse
import json
import keyword
import re
import sys
import textwrap
from dataclasses import dataclass, field
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs" / "sdk"
OUT = ROOT / "python" / "opense4"

HEADER = '"""{doc}\n\nGenerated by tools/gen_sdk_python.py from {sources}. Do not edit.\n"""\n'

# ---- Reading the docs ------------------------------------------------------------------------


@dataclass
class Row:
    name: str
    type: str = ""
    meaning: str = ""
    used: str = ""      # an order kind's "Fields used"


@dataclass
class Section:
    name: str
    file: str
    group: str            # the "## " heading it is under
    is_enum: bool = False
    rows: list = field(default_factory=list)
    prose: list = field(default_factory=list)


@dataclass
class Query:
    name: str
    args: list = field(default_factory=list)
    results: list = field(default_factory=list)


def cells(line: str) -> list:
    parts = line.strip().split("|")
    return [p.strip() for p in parts[1:-1]]


def ticks(s: str) -> str:
    return s.replace("`", "")


def read_doc(path: Path, sections: dict, queries: dict) -> None:
    group = ""
    cur = None
    query = None
    header = None
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("## ") or line.startswith("# "):
            group = line.lstrip("#").strip()
            cur = query = header = None
            continue
        if line.startswith("### "):
            m = re.search(r"`([^`]+)`", line)
            header = None
            if m:
                name = m.group(1)
                if name in sections:
                    raise SystemExit(f"{path.name}: `{name}` is documented twice")
                cur = sections[name] = Section(name, path.name, group)
                query = None
            else:
                cur = None
                query = None
                if group == "Queries":
                    qname = line[4:].strip()
                    query = queries[qname] = Query(qname)
            continue
        if line.startswith("|"):
            c = cells(line)
            if header is None:
                header = c
                if cur is not None:
                    cur.is_enum = header[0] == "Value"
                continue
            if set("".join(c)) <= set("-: "):
                continue
            if cur is not None:
                if cur.is_enum:
                    used = c[header.index("Fields used")] if "Fields used" in header else ""
                    cur.rows.append(Row(ticks(c[0]), "", c[header.index("Meaning")], used))
                else:
                    cur.rows.append(Row(ticks(c[0]), c[1], c[2] if len(c) > 2 else ""))
            elif query is not None:
                query.args.append(Row(ticks(c[0]), c[1], c[2] if len(c) > 2 else ""))
            continue
        header = None if not line.strip() else header
        if query is not None and line.startswith("Result:"):
            query.results = re.findall(r"`([^`]+)`", line)
        if cur is not None and line.strip() and not cur.rows:
            cur.prose.append(line.strip())


SECTIONS: dict = {}
QUERIES: dict = {}
read_doc(DOCS / "view.md", SECTIONS, QUERIES)
read_doc(DOCS / "commands.md", SECTIONS, QUERIES)

ENUMS = {n: s for n, s in SECTIONS.items() if s.is_enum}
STRUCTS = {n: s for n, s in SECTIONS.items() if not s.is_enum}
COMMAND_GROUPS = ("Vehicles and fleets", "Construction", "Colonies", "Designs", "Research and intelligence", "Diplomacy",
                  "Empire settings and lists")
COMMANDS = {n: s for n, s in STRUCTS.items() if s.file == "commands.md" and s.group in COMMAND_GROUPS}
COMMAND_TYPES = {n: s for n, s in STRUCTS.items()
                 if s.file == "commands.md" and (s.group == "Types the commands carry" or n == "square") and n not in COMMANDS}
RECORDS = {n: s for n, s in STRUCTS.items() if n not in COMMANDS and n != "empire_orders"}

# The enumeration of the view's turn styles has a table of its own; maps keyed by an
# enumeration (characteristics, sight_levels) are structs.

ID_KINDS = ("system", "object", "empire", "vehicle", "fleet", "design", "message")

# Classes the hand-written modules extend (opense4.view, opense4.rules): generated as
# <Name>Fields, the final <Name> lives there.
EXTENDED_VIEW = {"view": "View", "game": "Game", "my_empire": "MyEmpire", "empire": "Empire", "system": "System",
                 "space_object": "SpaceObject", "colony": "Colony", "vehicle": "Vehicle", "fleet": "Fleet",
                 "view_design": "Design", "message": "Message", "location": "Location", "resources": "Resources",
                 "battle": "Battle"}
EXTENDED_RULES = {"rules_view": "Rules", "component": "Component", "facility": "Facility", "hull": "Hull", "tech": "Tech"}
RENAMED = {"design": "DesignSpec"}
# Id fields resolved under other names (the object, the raw id): a planet's `colony` is the
# colony's owner, and the view's `empire` is ours (view.empire(id) looks empires up).
RESOLVE_AS = {("space_object", "colony"): ("colony_owner", "colony_owner_id"), ("view", "empire"): ("me", "empire_id")}
# The view lookup for each kind of id (View.resolve).
RESOLVED_CLASS = {"system": "System", "object": "SpaceObject", "empire": "Empire", "vehicle": "Vehicle",
                  "fleet": "Fleet", "design": "Design", "message": "Message"}


def is_entity(section: str) -> bool:
    """Records with an id of their own: equal when their ids are, usable as dict keys."""
    s = SECTIONS[section]
    return section in ("colony", "message") or (s.file == "view.md" and any(r.name == "id" for r in s.rows))


def camel(name: str) -> str:
    return "".join(p[:1].upper() + p[1:] for p in name.split("_"))


def class_name(section: str) -> str:
    if section in EXTENDED_VIEW:
        return EXTENDED_VIEW[section]
    if section in EXTENDED_RULES:
        return EXTENDED_RULES[section]
    return RENAMED.get(section, camel(section))


def generated_class(section: str) -> str:
    if section in EXTENDED_VIEW or section in EXTENDED_RULES:
        return class_name(section) + "Fields"
    return class_name(section)


@dataclass
class Type:
    base: str              # int, bool, text, any, id, ref, index, enum, struct, command
    name: str = ""         # the id kind, enum or struct name
    is_list: bool = False
    nullable: bool = False
    item_nullable: bool = False


def parse_type(t: str) -> Type:
    t = ticks(t).strip()
    nullable = False
    if t.endswith(", or null"):
        nullable = True
        t = t[: -len(", or null")]
    is_list = False
    if t.startswith("list of "):
        is_list = True
        t = t[len("list of "):]
    item_nullable = False
    if t.endswith(" or null"):
        item_nullable = True
        t = t[: -len(" or null")]
    if t in ("int", "bool", "text"):
        return Type(t, "", is_list, nullable, item_nullable)
    if t == "int or text":
        return Type("any", "", is_list, nullable, item_nullable)
    if t == "command":
        return Type("command", "", is_list, nullable, item_nullable)
    words = t.split(" ")
    if len(words) == 2 and words[1] == "id" and words[0] in ID_KINDS:
        return Type("id", words[0], is_list, nullable, item_nullable)
    if words[-1] == "ref":
        return Type("ref", " ".join(words[:-1]), is_list, nullable, item_nullable)
    if words[-1] == "index":
        return Type("index", " ".join(words[:-1]), is_list, nullable, item_nullable)
    if t in ENUMS:
        return Type("enum", t, is_list, nullable, item_nullable)
    if t in STRUCTS:
        return Type("struct", t, is_list, nullable, item_nullable)
    raise SystemExit(f"unknown type '{t}'")


def py_hint(ty: Type, final: bool = True) -> str:
    if ty.base == "int" or ty.base in ("ref", "index"):
        h = "int"
    elif ty.base == "bool":
        h = "bool"
    elif ty.base == "text" or ty.base == "enum":
        h = "str"
    elif ty.base == "any":
        h = "Union[int, str]"
    elif ty.base == "command":
        h = "Dict[str, Any]"
    elif ty.base == "id":
        h = RESOLVED_CLASS[ty.name]
    else:
        h = class_name(ty.name)
    if ty.item_nullable:
        h = f"Optional[{h}]"
    if ty.is_list:
        h = f"List[{h}]"
    if ty.nullable or (ty.base == "id" and not ty.is_list):
        h = f"Optional[{h}]"
    return h


def raw_hint(ty: Type) -> str:
    h = "int"
    if ty.is_list:
        h = "List[int]"
    if ty.nullable or not ty.is_list:
        h = f"Optional[{h}]"
    return h


def doc_text(s: str) -> str:
    s = re.sub(r"\[([^\]]+)\]\([^)]*\)", r"\1", s)   # [text](link) -> text
    s = ticks(s).replace('"""', "'''").replace("\\", "\\\\")
    return s.strip()


def wrapped(text: str, indent: str, width: int = 100) -> str:
    """`text` filled to `width` columns, every line after the first indented."""
    lines = textwrap.wrap(text, width=width - len(indent), break_long_words=False, break_on_hyphens=False)
    return ("\n" + indent).join(lines)


def summary(section: Section) -> str:
    text = " ".join(section.prose).strip()
    return doc_text(text) if text else ""


def referenced_meaning(name: str) -> str:
    """What the first field of this type says of it, for a type the docs give no prose."""
    for other in SECTIONS.values():
        for r in other.rows:
            if not r.type:
                continue
            words = re.split(r"[ ,`]+", r.type)
            if name in words:
                return doc_text(r.meaning)
    return ""


def ids_name(field_name: str) -> str:
    base = field_name[:-1] if field_name.endswith("s") else field_name
    return base + "_ids"


# ---- enums.py -------------------------------------------------------------------------------------


def gen_enums() -> str:
    out = [HEADER.format(doc="The enumerations of the SDK's interface (docs/sdk/view.md, docs/sdk/commands.md): each is\n"
                             "a tuple of its value names, in the engine's order",
                         sources="docs/sdk/view.md and docs/sdk/commands.md")]
    out.append("from __future__ import annotations\n\nfrom typing import Dict, Tuple\n\n")
    names = sorted(ENUMS)
    for n in names:
        s = ENUMS[n]
        out.append(f"{n.upper()}: Tuple[str, ...] = (\n")
        for r in s.rows:
            out.append(f"    {r.name!r},  # {doc_text(r.meaning)}\n")
        out.append(")\n\n")
    out.append("# Every enumeration by its name in the docs.\nALL: Dict[str, Tuple[str, ...]] = {\n")
    for n in names:
        out.append(f"    {n!r}: {n.upper()},\n")
    out.append("}\n")
    return "".join(out)


# ---- _records.py -----------------------------------------------------------------------------------


def gen_records() -> str:
    out = [HEADER.format(doc="Typed records over the SDK's values (docs/sdk/view.md, docs/sdk/commands.md): one class\n"
                             "per documented type, one property per field. opense4.view and opense4.rules extend the\n"
                             "classes whose names end in Fields",
                         sources="docs/sdk/view.md and docs/sdk/commands.md")]
    out.append("from __future__ import annotations\n\n")
    out.append("from typing import TYPE_CHECKING, Any, Dict, List, Optional, Tuple, Union\n\n")
    out.append("from ._record import CLASSES, Entity, Record, wrap, wrap_list\n\n")
    finals = sorted({class_name(n) for n in list(EXTENDED_VIEW) + list(EXTENDED_RULES)})
    view_finals = sorted({EXTENDED_VIEW[n] for n in EXTENDED_VIEW})
    rules_finals = sorted({EXTENDED_RULES[n] for n in EXTENDED_RULES})
    out.append("if TYPE_CHECKING:\n")
    out.append(f"    from .view import {', '.join(view_finals)}\n")
    out.append(f"    from .rules import {', '.join(rules_finals)}\n\n")
    fields_table = []
    for n in sorted(RECORDS, key=lambda k: (RECORDS[k].file, k)):
        s = RECORDS[n]
        cls = generated_class(n)
        base = "Entity" if is_entity(n) else "Record"
        out.append(f"\nclass {cls}({base}):\n")
        doc = summary(s) or referenced_meaning(n) or f"The type {n} of {s.file}."
        out.append(f'    """{wrapped(doc, "    ")}"""\n\n')
        out.append(f"    _kind = {n!r}\n")
        names_used = set()
        fields_table.append((n, [r.name for r in s.rows]))
        for r in s.rows:
            ty = parse_type(r.type)
            fname = r.name
            if keyword.iskeyword(fname):
                raise SystemExit(f"{n}.{fname} is a Python keyword")
            meaning = doc_text(r.meaning)
            resolve = ty.base == "id" and fname != "id"
            if resolve:
                prop, raw = RESOLVE_AS.get((n, fname), (fname, fname + "_id" if not ty.is_list else ids_name(fname)))
                for p in (prop, raw):
                    if p in names_used:
                        raise SystemExit(f"{n}.{p} is generated twice")
                    names_used.add(p)
                hint = py_hint(ty)
                out.append("\n    @property\n")
                out.append(f"    def {prop}(self) -> {hint}:\n")
                out.append(f'        """{wrapped(meaning, "        ")}"""\n')
                if ty.is_list:
                    if ty.nullable:
                        out.append(f"        ids = self._d[{fname!r}]\n")
                        out.append(f"        return None if ids is None else self._v.resolve_all({ty.name!r}, ids)\n")
                    else:
                        out.append(f"        return self._v.resolve_all({ty.name!r}, self._d[{fname!r}])\n")
                else:
                    out.append(f"        return self._v.resolve({ty.name!r}, self._d[{fname!r}])\n")
                out.append("\n    @property\n")
                out.append(f"    def {raw}(self) -> {raw_hint(ty)}:\n")
                out.append(f'        """The id{"s" if ty.is_list else ""} of `{prop}`."""\n')
                out.append(f"        return self._d[{fname!r}]\n")
                continue
            if fname in names_used:
                raise SystemExit(f"{n}.{fname} is generated twice")
            names_used.add(fname)
            hint = ("Optional[int]" if ty.nullable else "int") if ty.base == "id" else py_hint(ty)
            out.append("\n    @property\n")
            out.append(f"    def {fname}(self) -> {hint}:\n")
            out.append(f'        """{wrapped(meaning, "        ")}"""\n')
            if ty.base == "struct":
                fn = "wrap_list" if ty.is_list else "wrap"
                out.append(f"        return {fn}({ty.name!r}, self._v, self._d[{fname!r}])\n")
            else:
                out.append(f"        return self._d[{fname!r}]\n")
        out.append("\n\n")
    out.append("# The final class of each type, by its name in the docs. opense4.view and opense4.rules put\n")
    out.append("# their own classes in place of the ...Fields ones.\n")
    for n in sorted(RECORDS):
        if n in EXTENDED_VIEW or n in EXTENDED_RULES:
            continue
        out.append(f"CLASSES[{n!r}] = {generated_class(n)}\n")
    out.append("\n# The fields of every type, in the docs' order.\nFIELDS: Dict[str, Tuple[str, ...]] = {\n")
    for n, fields in sorted(fields_table):
        out.append(f"    {n!r}: ({', '.join(repr(f) for f in fields)}{',' if len(fields) == 1 else ''}),\n")
    out.append("}\n")
    # The queries: their arguments and result types (docs/sdk/view.md, "Queries").
    out.append("\n# Every query (docs/sdk/view.md, \"Queries\"): its arguments and the types of its result.\n")
    out.append("QUERIES: Dict[str, Tuple[Tuple[str, ...], Tuple[str, ...]]] = {\n")
    for q in QUERIES.values():
        args = ", ".join(repr(a.name) for a in q.args)
        res = ", ".join(repr(r) for r in q.results if r in STRUCTS)
        out.append(f"    {q.name!r}: (({args}{',' if len(q.args) == 1 else ''}), ({res}{',' if len([r for r in q.results if r in STRUCTS]) == 1 else ''})),\n")
    out.append("}\n")
    return "".join(out)


# ---- Constructors ----------------------------------------------------------------------------------

# Defaults the meaning column states in words, beyond what heuristics find; checked against
# the engine's codec by the tests.
DEFAULT_OVERRIDES: dict = {}


def default_of(section: str, row: Row) -> object:
    if (section, row.name) in DEFAULT_OVERRIDES:
        return DEFAULT_OVERRIDES[(section, row.name)]
    ty = parse_type(row.type)
    meaning = ticks(row.meaning)
    if ty.nullable or ty.base in ("id", "ref") and not ty.is_list:
        return None
    # The table names a default ("-1 by default", "1 neutral (the default)", "(true by default)");
    # otherwise a number is 0, a flag false, a list empty, an enumeration its first value
    # (docs/sdk/commands.md, "Conventions").
    if ty.is_list:
        m = re.search(r"(\[[^\]]*\]) by default", meaning)
        return json.loads(m.group(1)) if m else []
    if ty.base == "int" or ty.base == "index":
        m = re.search(r"(-?\d+) by default", meaning) or re.search(r"(-?\d+) (?:\w+ )?\(the default\)", meaning)
        return int(m.group(1)) if m else 0
    if ty.base == "bool":
        if "(false by default" in meaning:
            return False
        return "(true by default" in meaning or "(the default)" in meaning
    if ty.base == "text":
        return ""
    if ty.base == "enum":
        names = [r.name for r in ENUMS[ty.name].rows]
        m = re.search(r"\((\w+) by default", meaning)
        return m.group(1) if m and m.group(1) in names else names[0]
    if ty.base == "struct":
        return {r.name: default_of(ty.name, r) for r in STRUCTS[ty.name].rows}
    if ty.base == "any":
        return 0
    raise SystemExit(f"no default for {section}.{row.name}")


def converter(section: str, row: Row, value: str) -> str:
    """The expression that converts argument `value` of field `row`."""
    ty = parse_type(row.type)
    where = f"{section}.{row.name}"
    if ty.base == "id":
        if ty.is_list:
            return f"_ids({value}, {ty.name!r}, {where!r})"
        return f"_id({value}, {ty.name!r}, {where!r})"
    if ty.base == "ref":
        return f"_ref({value}, {ty.name!r}, {where!r})"
    if ty.base == "index":
        if ty.is_list:
            return f"_indices({value}, {where!r})"
        return f"_index({value}, {where!r}{', True' if ty.nullable else ''})"
    if ty.base in ("int", "bool", "text"):
        if ty.is_list:
            return f"_list_of_{ty.base}({value}, {where!r})"
        return f"_{ty.base}({value}, {where!r}{', True' if ty.nullable else ''})"
    if ty.base == "enum":
        if ty.is_list:
            return f"_enums({value}, enums.{ty.name.upper()}, {where!r}{', True' if ty.nullable else ''})"
        return f"_enum({value}, enums.{ty.name.upper()}, {where!r}{', True' if ty.nullable else ''})"
    if ty.base == "struct":
        if ty.name == "order" and ty.is_list:
            return f"_orders({value}, {where!r})"
        if ty.is_list:
            return f"_structs({value}, {ty.name!r}, {where!r})"
        return f"_struct({value}, {ty.name!r}, {where!r}{', True' if ty.nullable else ''})"
    if ty.base == "any":
        return f"_int_or_text({value}, {where!r})"
    raise SystemExit(f"no converter for {where}")


def param_hint(row: Row) -> str:
    ty = parse_type(row.type)
    if ty.base == "id":
        h = "Ref"
    elif ty.base in ("ref", "index"):
        h = "Ref"
    elif ty.base == "int":
        h = "int"
    elif ty.base == "bool":
        h = "bool"
    elif ty.base in ("text", "enum"):
        h = "str"
    elif ty.base == "struct":
        h = {"location": "LocationLike", "resources": "ResourcesLike", "queue_target": "TargetLike",
             "order": "Dict[str, Any]"}.get(ty.name, "Dict[str, Any]")
    else:
        h = "Any"
    if ty.is_list:
        h = f"Sequence[{h}]"
    if ty.base == "struct" or ty.is_list or ty.nullable or ty.base in ("id", "ref"):
        h = f"Optional[{h}]"
    return h


def signature_default(section: str, row: Row) -> str:
    ty = parse_type(row.type)
    if ty.base == "struct" or ty.is_list or ty.nullable or ty.base in ("id", "ref"):
        return "None"
    return repr(default_of(section, row))


# Fields converted by a function of their own (a battle piece may be given as the piece).
SPECIAL = {("tactical_order", "piece"): "_piece", ("tactical_order", "target"): "_piece"}


def body_value(section: str, row: Row, arg: str, kind: str = "") -> str:
    ty = parse_type(row.type)
    where = f"{kind or section}.{row.name}"
    if (section, row.name) in SPECIAL:
        return f"{SPECIAL[(section, row.name)]}({arg}, {where!r})"
    if section == "order" and kind == "stellar_manipulation" and row.name == "amount":
        return f"_stellar({arg}, {where!r})"
    conv = converter(kind or section, row, arg)
    if ty.base == "struct" and not ty.nullable and not ty.is_list:
        return f"{default_of(section, row)!r} if {arg} is None else {conv}"
    if ty.is_list and not ty.nullable:
        return f"{default_of(section, row)!r} if {arg} is None else {conv}"
    return conv


def gen_constructor(name: str, section: str, rows: list, params: list, doc: str, kind_value, out: list,
                    keyword_only_after: int = -1) -> None:
    """A function `name` taking `params` (rows) and building a map of every row."""
    sig = []
    for i, r in enumerate(params):
        if i == keyword_only_after:
            sig.append("*")
        sig.append(f"{r.name}: {param_hint(r)} = {signature_default(section, r)}")
    out.append(f"\ndef {name}({', '.join(sig)}) -> Dict[str, Any]:\n")
    out.append(f'    """{wrapped(doc, "    ")}')
    pnames = {r.name for r in params}
    if params:
        out.append("\n\n")
        for r in params:
            out.append(f"    {wrapped(r.name + ': ' + doc_text(r.meaning), '        ')}\n")
        out.append("    ")
    out.append('"""\n')
    items = []
    if kind_value is not None:
        items.append(f"'kind': {kind_value!r}")
    for r in rows:
        if r.name in pnames:
            items.append(f"{r.name!r}: {body_value(section, r, r.name, kind_value or '')}")
        else:
            items.append(f"{r.name!r}: {repr(default_of(section, r))}")
    out.append("    return {\n")
    for it in items:
        out.append(f"        {it},\n")
    out.append("    }\n\n")


CONSTRUCTOR_IMPORTS = ("from __future__ import annotations\n\n"
                       "from typing import Any, Dict, List, Optional, Sequence\n\n"
                       "from . import enums\n"
                       "from ._values import (LocationLike, Ref, ResourcesLike, TargetLike, _bool, _enum, _enums, _id, _ids, _index,\n"
                       "                      _indices, _int, _int_or_text, _list_of_int, _list_of_text, _orders, _piece, _ref,\n"
                       "                      _stellar, _struct, _structs, _text)\n\n")


def gen_commands() -> str:
    out = [HEADER.format(doc="A constructor for every command (docs/sdk/commands.md) and every type a command carries.\n"
                             "Each builds the command's map with every field: what you leave out is the engine's default.\n"
                             "Ids may be given as ids or as the view's objects (a Vehicle for a vehicle id)",
                         sources="docs/sdk/commands.md")]
    out.append(CONSTRUCTOR_IMPORTS)
    for name, s in COMMANDS.items():
        gen_constructor(name, name, s.rows, s.rows, summary(s), name, out)
    out.append("\n# ---- Types the commands carry --------------------------------------------------------------\n")
    for name, s in COMMAND_TYPES.items():
        gen_constructor(name, name, s.rows, s.rows, summary(s) or f"A {name} (docs/sdk/commands.md).", None, out)
    out.append("\n# Every command kind, in the docs' order.\nCOMMAND_KINDS = (\n")
    for name in COMMANDS:
        out.append(f"    {name!r},\n")
    out.append(")\n\n# The types above, by name.\nTYPES = (\n")
    for name in COMMAND_TYPES:
        out.append(f"    {name!r},\n")
    out.append(")\n\n")
    out.append("# The orders, the tactical orders, and helpers written by hand (opense4/_cmd_extra.py).\n")
    out.append("from . import order, tactical  # noqa: E402\n")
    out.append("from ._cmd_extra import build, centre, give, only, without  # noqa: E402\n")
    return "".join(out)


def used_fields(row: Row, all_rows: list) -> list:
    words = re.split(r"[ ,]+", ticks(row.used).replace(" or ", " "))
    names = [r.name for r in all_rows]
    used = []
    for w in words:
        if w in names and w not in used:
            used.append(w)
    return used


def gen_orders(section: str, kinds_section: str, title: str, fixed: dict) -> str:
    s = STRUCTS[section]
    kinds = ENUMS[kinds_section]
    out = [HEADER.format(doc=title, sources="docs/sdk/commands.md")]
    out.append(CONSTRUCTOR_IMPORTS)
    rows = {r.name: r for r in s.rows}
    for k in kinds.rows:
        used = [rows[u] for u in used_fields(k, s.rows) if u != "kind"]
        extra = [rows[f] for f in fixed if f in rows and rows[f] not in used]
        params = used + extra
        name = k.name + ("_" if keyword.iskeyword(k.name) else "")
        doc = doc_text(k.meaning)
        gen_constructor(name, section, [r for r in s.rows if r.name != "kind"], params, doc, k.name, out,
                        keyword_only_after=len(used) if extra else -1)
    out.append(f"\n# Every kind, in the docs' order.\nKINDS = (\n")
    for k in kinds.rows:
        out.append(f"    {k.name!r},\n")
    out.append(")\n")
    return "".join(out)


def generate() -> dict:
    return {
        "enums.py": gen_enums(),
        "_records.py": gen_records(),
        "cmd.py": gen_commands(),
        "order.py": gen_orders("order", "order_kind",
                               "A constructor for every order kind (docs/sdk/commands.md, \"Orders\"): the orders of\n"
                               "set_orders and order_tagged. Each takes the fields its kind uses, and builds the order's map\n"
                               "with every field", {}),
        "tactical.py": gen_orders("tactical_order", "tactical_order_kind",
                                  "A constructor for every tactical order kind (docs/sdk/commands.md, \"Tactical battles\"),\n"
                                  "the answer to battle_round. Each takes the fields its kind uses (and the side giving it,\n"
                                  "which opense4.ai fills in), and builds the order's map with every field", {"empire": True}),
    }


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--check", action="store_true", help="exit 1 when a generated file is out of date")
    args = ap.parse_args()
    stale = []
    for name, text in generate().items():
        path = OUT / name
        old = path.read_text(encoding="utf-8") if path.exists() else None
        if old == text:
            continue
        stale.append(name)
        if not args.check:
            path.write_text(text, encoding="utf-8")
    if args.check and stale:
        print("out of date (run tools/gen_sdk_python.py): " + ", ".join(stale))
        return 1
    if not args.check:
        print("wrote " + (", ".join(stale) if stale else "nothing (all up to date)"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
