#!/usr/bin/env python3
"""Generates the API reference of the `opense4` Python package (docs/sdk/reference/*.md)
from its source: the docstrings and type hints of python/opense4.

    python3 tools/gen_sdk_reference.py           # writes docs/sdk/reference/
    python3 tools/gen_sdk_reference.py --check   # exits 1 when a page is out of date

It reads the package with `ast` and imports nothing, so the pages do not depend on the
Python that makes them. Every public module gets a page: its docstring, then its
classes (constructor, fields, properties and methods, with the members of the private
classes they extend: the generated `_records.*Fields` and helpers such as
`rules._Abilities`), its functions and its documented constants. Names that a module
takes from a private module (`from ._cmd_extra import give`) are documented where they
are offered. The record types that no public class extends get a page of their own.

The SDK's tests run --check (tests/sdk/test_sdk_guide.cpp): change the package, run
this, commit the pages.
"""

from __future__ import annotations

import argparse
import ast
import inspect
import re
import sys
import textwrap
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional, Tuple

ROOT = Path(__file__).resolve().parent.parent
PACKAGE = ROOT / "python" / "opense4"
OUT = ROOT / "docs" / "sdk" / "reference"

GENERATED = ("<!-- Generated by tools/gen_sdk_reference.py from python/opense4. Do not edit: change the package's "
             "docstrings and run the tool. -->")

# The public modules, in the order the index lists them.
MODULES = [
    ("opense4", "__init__.py"),
    ("opense4.ai", "ai.py"),
    ("opense4.builtin", "builtin.py"),
    ("opense4.view", "view.py"),
    ("opense4.galaxy", "galaxy.py"),
    ("opense4.rules", "rules.py"),
    ("opense4.cmd", "cmd.py"),
    ("opense4.order", "order.py"),
    ("opense4.tactical", "tactical.py"),
    ("opense4.services", "services.py"),
    ("opense4.rng", "rng.py"),
    ("opense4.enums", "enums.py"),
    ("opense4.testing", "testing.py"),
    ("opense4.external", "external.py"),
    ("opense4.bot", "bot.py"),
    ("opense4.env", "env.py"),
]
RECORDS_PAGE = "opense4.records"


# ---- Reading the source ------------------------------------------------------------------------


@dataclass
class Source:
    name: str
    path: Path
    text: str
    tree: ast.Module
    lines: List[str]

    def segment(self, node: Optional[ast.AST]) -> str:
        if node is None:
            return ""
        s = ast.get_source_segment(self.text, node) or ""
        return " ".join(s.split())


def read(path: Path, name: str) -> Source:
    text = path.read_text(encoding="utf-8")
    return Source(name, path, text, ast.parse(text, str(path)), text.splitlines())


def docstring(node: ast.AST) -> str:
    d = ast.get_docstring(node, clean=True)  # type: ignore[arg-type]
    return d or ""


def first_line(doc: str) -> str:
    """The docstring's first sentence or line, for the index."""
    para = doc.strip().split("\n\n")[0].replace("\n", " ")
    m = re.match(r"(.+?\.)(\s|$)", para)
    text = (m.group(1) if m else para).strip()
    return text[:-1] + "." if text.endswith(":") else text


def is_public(name: str) -> bool:
    return not name.startswith("_")


def module_all(src: Source) -> Optional[List[str]]:
    for node in src.tree.body:
        if isinstance(node, ast.Assign) and any(isinstance(t, ast.Name) and t.id == "__all__" for t in node.targets):
            if isinstance(node.value, (ast.List, ast.Tuple)):
                return [e.value for e in node.value.elts if isinstance(e, ast.Constant) and isinstance(e.value, str)]
    return None


# ---- Rendering docstrings ------------------------------------------------------------------------

ARG_LINE = re.compile(r"^([A-Za-z_][A-Za-z0-9_]*(?:, [A-Za-z_][A-Za-z0-9_]*)*): (.*)$")


def render_doc(doc: str) -> str:
    """A docstring as Markdown: indented blocks become Python code, `name: text` lines a
    list of arguments, `- ` lines stay a list, the rest paragraphs."""
    if not doc:
        return ""
    out: List[str] = []
    code: List[str] = []   # the lines of the code block being gathered

    def flush() -> None:
        if code:
            out.append("```python\n" + textwrap.dedent("\n".join(code)).strip("\n") + "\n```")
            code.clear()

    for para in re.split(r"\n\s*\n", doc.strip("\n")):
        lines = para.split("\n")
        if all(l.startswith("    ") or not l.strip() for l in lines):
            if code:
                code.append("")
            code.extend(lines)
            continue
        flush()
        if ARG_LINE.match(lines[0]) and all(ARG_LINE.match(l) or l.startswith(" ") for l in lines):
            items: List[str] = []
            for l in lines:
                m = ARG_LINE.match(l)
                if m:
                    items.append(f"- `{m.group(1)}`: {m.group(2)}")
                else:
                    items[-1] += " " + l.strip()
            out.append("\n".join(items))
            continue
        if lines[0].startswith("- "):
            items = []
            for l in lines:
                if l.startswith("- "):
                    items.append(l)
                else:
                    items[-1] += " " + l.strip()
            out.append("\n".join(items))
            continue
        out.append(" ".join(l.strip() for l in lines))
    flush()
    return "\n\n".join(out)


def cell(text: str) -> str:
    """Text for a table cell: one line, pipes escaped."""
    return " ".join(text.split()).replace("|", "\\|")


# ---- Signatures --------------------------------------------------------------------------------


def signature(src: Source, fn: ast.FunctionDef, drop_self: bool) -> str:
    a = fn.args
    parts: List[str] = []
    positional = list(a.posonlyargs) + list(a.args)
    defaults: List[Optional[ast.expr]] = [None] * (len(positional) - len(a.defaults)) + list(a.defaults)
    for i, (arg, default) in enumerate(zip(positional, defaults)):
        if i == 0 and drop_self and arg.arg in ("self", "cls"):
            continue
        parts.append(param(src, arg, default))
        if a.posonlyargs and arg is a.posonlyargs[-1]:
            parts.append("/")
    if a.vararg is not None:
        parts.append("*" + param(src, a.vararg, None))
    elif a.kwonlyargs:
        parts.append("*")
    for arg, default in zip(a.kwonlyargs, a.kw_defaults):
        parts.append(param(src, arg, default))
    if a.kwarg is not None:
        parts.append("**" + param(src, a.kwarg, None))
    ret = f" -> {src.segment(fn.returns)}" if fn.returns is not None else ""
    return f"{fn.name}({', '.join(parts)}){ret}"


def param(src: Source, arg: ast.arg, default: Optional[ast.expr]) -> str:
    s = arg.arg
    if arg.annotation is not None:
        s += ": " + src.segment(arg.annotation)
        if default is not None:
            s += " = " + src.segment(default)
    elif default is not None:
        s += "=" + src.segment(default)
    return s


def decorators(fn: ast.FunctionDef) -> List[str]:
    names = []
    for d in fn.decorator_list:
        if isinstance(d, ast.Name):
            names.append(d.id)
        elif isinstance(d, ast.Attribute):
            names.append(d.attr)
    return names


# ---- Classes -----------------------------------------------------------------------------------


@dataclass
class Member:
    kind: str           # "property", "method", "staticmethod", "classmethod", "attribute", "alias"
    name: str
    text: str           # signature, type or target
    doc: str
    default: str = ""


@dataclass
class ClassDoc:
    name: str
    src: Source
    node: ast.ClassDef
    bases: List[str] = field(default_factory=list)          # public bases, as written
    inlined: List[str] = field(default_factory=list)        # private bases whose members are shown
    constructor: str = ""
    members: List[Member] = field(default_factory=list)


def class_members(src: Source, node: ast.ClassDef) -> Tuple[str, List[Member]]:
    constructor = ""
    members: List[Member] = []
    pending_doc: Dict[str, str] = {}
    body = node.body
    for i, item in enumerate(body):
        if isinstance(item, ast.FunctionDef):
            if item.name == "__init__":
                constructor = signature(src, item, True).replace("__init__", node.name, 1).split(" -> ")[0]
                continue
            if not is_public(item.name):
                continue
            decos = decorators(item)
            if "setter" in decos or "deleter" in decos:
                continue
            if "property" in decos or "cached_property" in decos:
                members.append(Member("property", item.name, src.segment(item.returns), docstring(item)))
            elif "staticmethod" in decos:
                members.append(Member("staticmethod", item.name, signature(src, item, False), docstring(item)))
            elif "classmethod" in decos:
                members.append(Member("classmethod", item.name, signature(src, item, True), docstring(item)))
            else:
                members.append(Member("method", item.name, signature(src, item, True), docstring(item)))
        elif isinstance(item, ast.AnnAssign) and isinstance(item.target, ast.Name) and is_public(item.target.id):
            doc = ""
            if i + 1 < len(body) and isinstance(body[i + 1], ast.Expr) and isinstance(body[i + 1].value, ast.Constant) \
                    and isinstance(body[i + 1].value.value, str):
                doc = inspect.cleandoc(body[i + 1].value.value)
            members.append(Member("attribute", item.target.id, src.segment(item.annotation), doc, src.segment(item.value)))
        elif isinstance(item, ast.Assign) and len(item.targets) == 1 and isinstance(item.targets[0], ast.Name) \
                and is_public(item.targets[0].id):
            name = item.targets[0].id
            if isinstance(item.value, ast.Name):
                members.append(Member("alias", name, item.value.id, ""))
            elif name not in ("_kind",):
                doc = ""
                if i + 1 < len(body) and isinstance(body[i + 1], ast.Expr) and isinstance(body[i + 1].value, ast.Constant) \
                        and isinstance(body[i + 1].value.value, str):
                    doc = inspect.cleandoc(body[i + 1].value.value)
                members.append(Member("attribute", name, "", doc, src.segment(item.value)))
    del pending_doc
    return constructor, members


def base_name(src: Source, b: ast.expr) -> str:
    return src.segment(b)


# ---- The package -------------------------------------------------------------------------------


class Package:
    def __init__(self) -> None:
        self.sources: Dict[str, Source] = {}
        for name, file in MODULES:
            self.sources[name] = read(PACKAGE / file, name)
        for path in sorted(PACKAGE.glob("_*.py")):
            if path.name == "__init__.py":
                continue
            name = "opense4." + path.stem
            self.sources[name] = read(path, name)
        self.records = self.sources["opense4._records"]
        self.record_classes: Dict[str, ast.ClassDef] = {
            n.name: n for n in self.records.tree.body if isinstance(n, ast.ClassDef)}
        self.extended: Dict[str, str] = {}   # _records class -> the public class that extends it

    def private_class(self, src: Source, base: str) -> Optional[Tuple[Source, ast.ClassDef]]:
        """A private class a public one extends: `_records.XFields` or a `_Name` of its own module."""
        if base.startswith("_records."):
            n = self.record_classes.get(base.split(".", 1)[1])
            return (self.records, n) if n is not None else None
        if base.startswith("_"):
            for node in src.tree.body:
                if isinstance(node, ast.ClassDef) and node.name == base:
                    return src, node
        return None

    def class_doc(self, src: Source, node: ast.ClassDef, public_name: str) -> ClassDoc:
        doc = ClassDoc(public_name, src, node)
        constructor, own = class_members(src, node)
        doc.constructor = constructor
        members: List[Member] = []
        seen = {m.name for m in own}
        for b in node.bases:
            bname = base_name(src, b)
            found = self.private_class(src, bname)
            if found is None:
                doc.bases.append(bname)
                continue
            bsrc, bnode = found
            doc.inlined.append(bname)
            if bsrc is self.records:
                self.extended[bnode.name] = f"{src.name}.{public_name}"
            for b2 in bnode.bases:
                b2name = base_name(bsrc, b2)
                if self.private_class(bsrc, b2name) is None and b2name not in ("Record", "Entity", "ABC"):
                    doc.bases.append(b2name)
            bconstructor, inherited = class_members(bsrc, bnode)
            if not doc.constructor and bsrc is not self.records:
                doc.constructor = bconstructor.replace(bnode.name, public_name, 1)
            for m in inherited:
                if m.name not in seen:
                    members.append(m)
                    seen.add(m.name)
        doc.members = members + own
        doc.bases = [b for b in doc.bases if b not in ("Record", "Entity")]
        return doc

    def module_items(self, name: str) -> List[Tuple[str, Source, ast.AST]]:
        """The public definitions of a module, in source order, with the names it takes
        from private modules of the package at the place it imports them."""
        src = self.sources[name]
        allowed = module_all(src)
        items: List[Tuple[str, Source, ast.AST]] = []
        body = src.tree.body
        for i, node in enumerate(body):
            if isinstance(node, (ast.FunctionDef, ast.ClassDef)) and is_public(node.name):
                items.append((node.name, src, node))
            elif isinstance(node, (ast.Assign, ast.AnnAssign)):
                target = node.targets[0] if isinstance(node, ast.Assign) else node.target
                if isinstance(target, ast.Name) and is_public(target.id) and target.id != "__all__" \
                        and target.id.upper() == target.id:
                    doc = ""
                    if i + 1 < len(body) and isinstance(body[i + 1], ast.Expr) and isinstance(body[i + 1].value, ast.Constant) \
                            and isinstance(body[i + 1].value.value, str):
                        doc = inspect.cleandoc(body[i + 1].value.value)
                    if doc or name == "opense4.enums" or isinstance(node, ast.AnnAssign):
                        items.append((target.id, src, node))
            elif isinstance(node, ast.ImportFrom) and node.level == 1 and node.module and node.module.startswith("_") \
                    and node.module not in ("_records", "_record", "_values", "_engine"):
                other = self.sources.get("opense4." + node.module)
                if other is None:
                    continue
                for alias in node.names:
                    for n in other.tree.body:
                        if isinstance(n, (ast.FunctionDef, ast.ClassDef)) and n.name == alias.name:
                            items.append((alias.asname or alias.name, other, n))
        if allowed is not None:
            items = [it for it in items if it[0] in allowed]
        return items


# ---- Pages -------------------------------------------------------------------------------------


def anchor(text: str) -> str:
    """GitHub's anchor for a heading."""
    t = text.strip().lower()
    t = re.sub(r"[^\w\- ]", "", t)
    return t.replace(" ", "-")


def page_link(module: str) -> str:
    return f"{module}.md"


def render_class(cd: ClassDoc, level: str = "##") -> List[str]:
    out = [f"{level} `{cd.name}`", ""]
    head = []
    if cd.constructor:
        head.append(f"```python\n{cd.constructor}\n```")
    if cd.bases:
        head.append("Extends " + ", ".join(f"`{b}`" for b in cd.bases) + ".")
    out += [h + "\n" for h in head]
    doc = render_doc(docstring(cd.node))
    if doc:
        out += [doc, ""]
    attributes = [m for m in cd.members if m.kind == "attribute"]
    properties = [m for m in cd.members if m.kind == "property"]
    methods = [m for m in cd.members if m.kind in ("method", "staticmethod", "classmethod")]
    aliases = [m for m in cd.members if m.kind == "alias"]
    if attributes:
        out += ["| Attribute | Type | Default | |", "|---|---|---|---|"]
        for m in attributes:
            out.append(f"| `{m.name}` | {('`' + cell(m.text) + '`') if m.text else ''} | "
                       f"{('`' + cell(m.default) + '`') if m.default else ''} | {cell(m.doc)} |")
        out.append("")
    if properties:
        out += ["| Property | Type | |", "|---|---|---|"]
        for m in properties:
            out.append(f"| `{m.name}` | {('`' + cell(m.text) + '`') if m.text else ''} | {cell(m.doc)} |")
        out.append("")
    for m in methods:
        prefix = "@staticmethod\n" if m.kind == "staticmethod" else "@classmethod\n" if m.kind == "classmethod" else ""
        out += [f"{level}# `{cd.name}.{m.name}`", "", f"```python\n{prefix}{m.text}\n```", ""]
        d = render_doc(m.doc)
        if d:
            out += [d, ""]
    for m in aliases:
        out += [f"`{cd.name}.{m.name}` is `{cd.name}.{m.text}`.", ""]
    return out


def render_function(src: Source, fn: ast.FunctionDef, name: str) -> List[str]:
    sig = signature(src, fn, False)
    if name != fn.name:
        sig = name + sig[len(fn.name):]
    out = [f"## `{name}`", "", f"```python\n{sig}\n```", ""]
    d = render_doc(docstring(fn))
    if d:
        out += [d, ""]
    return out


def enum_comments(src: Source, node: ast.AST) -> List[Tuple[str, str]]:
    value = node.value if isinstance(node, (ast.Assign, ast.AnnAssign)) else None
    rows = []
    if isinstance(value, ast.Tuple):
        for e in value.elts:
            if isinstance(e, ast.Constant):
                line = src.lines[e.lineno - 1]
                comment = line.split("#", 1)[1].strip() if "#" in line else ""
                rows.append((str(e.value), comment))
    return rows


def render_constant(src: Source, node: ast.AST, name: str, module: str) -> List[str]:
    i = src.tree.body.index(node)  # type: ignore[arg-type]
    doc = ""
    body = src.tree.body
    if i + 1 < len(body) and isinstance(body[i + 1], ast.Expr) and isinstance(body[i + 1].value, ast.Constant) \
            and isinstance(body[i + 1].value.value, str):
        doc = inspect.cleandoc(body[i + 1].value.value)
    if module == "opense4.enums":
        rows = enum_comments(src, node)
        if rows:
            out = [f"## `{name}`", "", "| Name | Meaning |", "|---|---|"]
            out += [f"| `{v}` | {cell(c)} |" for v, c in rows]
            return out + [""]
        value = src.segment(node.value)  # type: ignore[attr-defined]
        if len(value) > 160:
            value = value[:157] + "..."
        return [f"## `{name}`", "", f"`{name} = {value}`", "", render_doc(doc), ""] if doc else \
               [f"## `{name}`", "", f"`{name} = {value}`", ""]
    value = src.segment(node.value)  # type: ignore[attr-defined]
    if len(value) > 120:
        value = value[:117] + "..."
    out = [f"## `{name}`", "", f"```python\n{name} = {value}\n```", ""]
    if doc:
        out += [render_doc(doc), ""]
    return out


def render_module(pkg: Package, module: str) -> str:
    src = pkg.sources[module]
    items = pkg.module_items(module)
    out = [GENERATED, "", f"# `{module}`", ""]
    doc = render_doc(docstring(src.tree))
    if doc:
        out += [doc, ""]
    out += [f"Source: [python/opense4/{src.path.name}](../../../python/opense4/{src.path.name}). "
            f"Index: [the API reference](README.md).", ""]
    if items:
        out += ["Contents: " + ", ".join(f"[`{n}`](#{anchor(n)})" for n, _, _ in items) + ".", ""]
    for name, isrc, node in items:
        if isinstance(node, ast.ClassDef):
            out += render_class(pkg.class_doc(isrc, node, name))
        elif isinstance(node, ast.FunctionDef):
            out += render_function(isrc, node, name)
        else:
            out += render_constant(isrc, node, name, module)
    return "\n".join(out).rstrip() + "\n"


def render_records(pkg: Package) -> str:
    out = [GENERATED, "", "# The record types", "",
           "The view, the rules view and the commands carry these types as maps "
           "([view.md](../view.md), [commands.md](../commands.md)). The package wraps them in "
           "records: one class per type, one property per field, as the generated module "
           "`opense4._records` defines them. A field that holds an id gives the object it names, "
           "and the id under the same name with `_id` ([python-api.md](../python-api.md), \"The view\"). "
           "`opense4.view.record(kind, data, view)` wraps a map of one of these types by hand.", "",
           "The types that the public modules extend are on their pages: "
           + ", ".join(f"`{pub}`" for pub in sorted(set(pkg.extended.values()))) + ".", ""]
    names = [n for n in pkg.record_classes if n not in pkg.extended]
    out += ["Contents: " + ", ".join(f"[`{n}`](#{anchor(n)})" for n in names) + ".", ""]
    for n in names:
        out += render_class(pkg.class_doc(pkg.records, pkg.record_classes[n], n))
    return "\n".join(out).rstrip() + "\n"


def render_index(pkg: Package) -> str:
    out = [GENERATED, "", "# The `opense4` package: API reference", "",
           "Every public module of the package with its classes, functions and constants, generated "
           "from the package's own docstrings and type hints. The package runs in the game and in "
           "external bots alike ([python-api.md](../python-api.md) is its guide; the "
           "[modder's guide](../guide/computer-players.md) teaches it step by step).", "",
           "| Module | What it is |", "|---|---|"]
    for module, _ in MODULES:
        out.append(f"| [`{module}`]({page_link(module)}) | {cell(first_line(docstring(pkg.sources[module].tree)))} |")
    out.append(f"| [Record types]({page_link(RECORDS_PAGE)}) | The types of the view, the rules view and the "
               "commands, as records with a property per field. |")
    out += ["", "To make these pages again after changing the package:", "", "```sh",
            "python3 tools/gen_sdk_reference.py           # writes docs/sdk/reference/",
            "python3 tools/gen_sdk_reference.py --check   # exits 1 when a page is out of date", "```", ""]
    return "\n".join(out)


def pages() -> Dict[str, str]:
    pkg = Package()
    out: Dict[str, str] = {}
    for module, _ in MODULES:
        out[page_link(module)] = render_module(pkg, module)
    out[page_link(RECORDS_PAGE)] = render_records(pkg)   # after the modules: they record what they extend
    out["README.md"] = render_index(pkg)
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="exit 1 when a page differs from what the package gives")
    args = ap.parse_args()
    wanted = pages()
    if args.check:
        stale = []
        for name, text in wanted.items():
            path = OUT / name
            if not path.exists() or path.read_text(encoding="utf-8") != text:
                stale.append(name)
        extra = sorted(p.name for p in OUT.glob("*.md") if p.name not in wanted) if OUT.exists() else []
        if stale or extra:
            for name in stale:
                print(f"docs/sdk/reference/{name} is out of date")
            for name in extra:
                print(f"docs/sdk/reference/{name} is not made by the package any more")
            print("Run: python3 tools/gen_sdk_reference.py")
            return 1
        print(f"docs/sdk/reference: {len(wanted)} pages up to date")
        return 0
    OUT.mkdir(parents=True, exist_ok=True)
    for p in OUT.glob("*.md"):
        if p.name not in wanted:
            p.unlink()
    for name, text in wanted.items():
        path = OUT / name
        if not path.exists() or path.read_text(encoding="utf-8") != text:
            path.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {len(wanted)} pages to docs/sdk/reference")
    return 0


if __name__ == "__main__":
    sys.exit(main())
