#!/usr/bin/env bash
# Regenerates third_party/micropython, the MicroPython sources the script runtime is
# built from (docs/BUILDING.md, "MicroPython"; docs/sdk/runtime.md).
#
# MicroPython needs headers generated from its sources and our configuration (the
# qstr tables, the list of built-in modules and of GC roots). Generating them takes
# Python, make and a C preprocessor run over the sources, which not every compiler
# we build with can do the same way (MSVC, llvm-mingw, cross compilers). So this
# script does it once, on a Linux or macOS machine, and the result is committed:
#
#   1. downloads the pinned release and checks its SHA-256 (cached in build/_tools);
#   2. applies our changes, third_party/micropython/patches/*.patch;
#   3. runs MicroPython's embed port with src/script/port/mpconfigport.h to
#      generate the headers;
#   4. copies the sources we compile, the generated headers and the licences into
#      third_party/micropython, and records what it did in UPSTREAM.txt.
#
# Run it after changing mpconfigport.h (CMake stops the build until you do), after
# changing a patch, or to move to a new MicroPython release (update VERSION and
# SHA256 below, then refresh the patches against the new sources).
#
#   tools/update_micropython.sh
#
# Needs: bash, curl, tar with xz, patch, make, python3 and a C compiler (cc).

set -euo pipefail

VERSION=1.29.0
URL="https://github.com/micropython/micropython/releases/download/v${VERSION}/micropython-${VERSION}.tar.xz"
SHA256=d925a7c664e79a2bdf3dfcb285ba5e2237041cc35a0bd4ee573b6c5711efeca0

root=$(cd "$(dirname "$0")/.." && pwd)
out="$root/third_party/micropython"
port="$root/src/script/port"
cache="${OPENSE4_TOOLS_DIR:-$root/build/_tools}"
archive="$cache/micropython-${VERSION}.tar.xz"

sha256() {
    if command -v sha256sum >/dev/null; then sha256sum "$1" | cut -d' ' -f1; else shasum -a 256 "$1" | cut -d' ' -f1; fi
}

mkdir -p "$cache"
if [ ! -f "$archive" ] || [ "$(sha256 "$archive")" != "$SHA256" ]; then
    echo "Fetching $URL"
    curl -fL --retry 3 -o "$archive.part" "$URL"
    mv "$archive.part" "$archive"
fi
if [ "$(sha256 "$archive")" != "$SHA256" ]; then
    echo "error: $archive does not have the expected SHA-256 $SHA256" >&2
    exit 1
fi

work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT
tar -xJf "$archive" -C "$work"
src="$work/micropython-${VERSION}"
# The release's own date, so that the generated version header is the same every run.
SOURCE_DATE_EPOCH=$(stat -c %Y "$src/py/mpconfig.h" 2>/dev/null || stat -f %m "$src/py/mpconfig.h")
export SOURCE_DATE_EPOCH

for p in "$out"/patches/*.patch; do
    echo "Applying $(basename "$p")"
    patch -d "$src" -p1 --quiet --no-backup-if-mismatch < "$p"
done

# The embed port generates the headers from our configuration. The extension modules
# we use are added to the sources it scans for qstrs and module registrations.
gen="$work/gen"
mkdir -p "$gen"
cp "$port/mpconfigport.h" "$port/mphalport.h" "$gen/"
cat > "$gen/Makefile" <<EOF
MICROPYTHON_TOP = $src
PACKAGE_DIR = $work/package
SRC_QSTR += extmod/modjson.c extmod/modre.c extmod/modheapq.c
include \$(MICROPYTHON_TOP)/ports/embed/embed.mk
EOF
make -C "$gen" -j4 >/dev/null 2>&1 || make -C "$gen"

# Replace everything but our patches and the licence texts the release lacks.
find "$out" -mindepth 1 -maxdepth 1 ! -name patches ! -name licenses -exec rm -rf {} +
mkdir -p "$out/py" "$out/extmod" "$out/lib/re1.5" "$out/lib/libm_dbl" "$out/shared/runtime" "$out/genhdr"
cp "$work/package/py/"*.[ch] "$out/py/"
cp "$work/package/genhdr/"*.h "$out/genhdr/"
cp "$src/extmod/modjson.c" "$src/extmod/modre.c" "$src/extmod/modheapq.c" "$src/extmod/modplatform.h" "$out/extmod/"
cp "$src/lib/re1.5/"*.[ch] "$out/lib/re1.5/"
cp "$src/lib/libm_dbl/"*.[ch] "$src/lib/libm_dbl/README" "$out/lib/libm_dbl/"
cp "$src/shared/runtime/gchelper.h" "$src/shared/runtime/gchelper_generic.c" "$out/shared/runtime/"
cp "$src/LICENSE" "$out/LICENSE"

{
    echo "MicroPython ${VERSION}, generated by tools/update_micropython.sh. Do not edit by hand."
    echo
    echo "source: $URL"
    echo "sha256: $SHA256"
    echo "mpconfigport.h sha256: $(sha256 "$port/mpconfigport.h")"
    echo "patches:"
    for p in "$out"/patches/*.patch; do
        echo "  $(basename "$p") $(sha256 "$p")"
    done
    echo
    echo "Contents: py/ (the core), extmod/ (json, re, heapq), lib/re1.5 (the regular"
    echo "expression engine), lib/libm_dbl (math functions from musl), shared/runtime"
    echo "(GC register helper) and genhdr/ (headers generated for our configuration)."
    echo "LICENSE is MicroPython's MIT licence; lib/libm_dbl/README gives musl's."
} > "$out/UPSTREAM.txt"

echo "Updated $out (MicroPython ${VERSION})"
