"""A constructor for every command (docs/sdk/commands.md) and every type a command carries.
Each builds the command's map with every field: what you leave out is the engine's default.
Ids may be given as ids or as the view's objects (a Vehicle for a vehicle id)

Generated by tools/gen_sdk_python.py from docs/sdk/commands.md. Do not edit.
"""
from __future__ import annotations

from typing import Any, Dict, List, Optional, Sequence, Union

from . import enums
from ._values import (LocationLike, Ref, ResourcesLike, TargetLike, _bool, _enum, _enums, _id, _ids, _index,
                      _indices, _int, _int_or_text, _list_of_int, _list_of_text, _orders, _piece, _ref,
                      _stellar, _struct, _structs, _text)


def set_orders(vehicle: Optional[Ref] = None, fleet: Optional[Ref] = None, planet: Optional[Ref] = None, orders: Optional[Sequence[Dict[str, Any]]] = None, repeat: bool = False) -> Dict[str, Any]:
    """Replaces the order list of a vehicle, a fleet or a colony (name one of the three). The orders
    that start the new list and repeat the current one are kept as they are; every order after them
    is expanded the moment it is given, as in the classic game: Explore becomes a move to the
    nearest unexplored warp point and a warp, Resupply and Repair a move to the nearest place for
    them, and an order aimed somewhere else gets a Move To in front of it. A colony takes only
    Launch Units, Recover Units, Use Facility and Convert Resources.

    vehicle: The vehicle given the orders.
    fleet: Or the fleet.
    planet: Or one of our colonies, by its planet.
    orders: The new list (see Orders).
    repeat: Repeat the list when it ends (false by default).
    """
    return {
        'kind': 'set_orders',
        'vehicle': _id(vehicle, 'vehicle', 'set_orders.vehicle'),
        'fleet': _id(fleet, 'fleet', 'set_orders.fleet'),
        'planet': _id(planet, 'object', 'set_orders.planet'),
        'orders': [] if orders is None else _orders(orders, 'set_orders.orders'),
        'repeat': _bool(repeat, 'set_orders.repeat'),
    }


def order_tagged(vehicles: Optional[Sequence[Ref]] = None, orders: Optional[Sequence[Dict[str, Any]]] = None, repeat: bool = False) -> Dict[str, Any]:
    """An order given to several vehicles at once, as when the player tags vehicles in a sector's list:
    the orders are added to the end of each vehicle's own list, a fleet member standing for its
    whole fleet. The vehicles must share a sector. In a turn-based game they then act at once as one
    group.

    vehicles: The tagged vehicles, in the order they were tagged.
    orders: The orders to add.
    repeat: Switch Repeat on in each list.
    """
    return {
        'kind': 'order_tagged',
        'vehicles': [] if vehicles is None else _ids(vehicles, 'vehicle', 'order_tagged.vehicles'),
        'orders': [] if orders is None else _orders(orders, 'order_tagged.orders'),
        'repeat': _bool(repeat, 'order_tagged.repeat'),
    }


def create_fleet(name: str = '', members: Optional[Sequence[Ref]] = None) -> Dict[str, Any]:
    """Forms a new fleet of vehicles that share a sector; the first one leads it.

    name: The fleet's name.
    members: Its vehicles; the first leads.
    """
    return {
        'kind': 'create_fleet',
        'name': _text(name, 'create_fleet.name'),
        'members': [] if members is None else _ids(members, 'vehicle', 'create_fleet.members'),
    }


def join_fleet(fleet: Optional[Ref] = None, vehicle: Optional[Ref] = None) -> Dict[str, Any]:
    """A vehicle joins a fleet in its sector. Its own orders are cleared: it gets the fleet's later
    orders only.

    fleet: The fleet.
    vehicle: The vehicle that joins.
    """
    return {
        'kind': 'join_fleet',
        'fleet': _id(fleet, 'fleet', 'join_fleet.fleet'),
        'vehicle': _id(vehicle, 'vehicle', 'join_fleet.vehicle'),
    }


def leave_fleet(vehicle: Optional[Ref] = None) -> Dict[str, Any]:
    """The vehicle leaves its fleet, and its orders are cleared. A fleet left with no member at its
    location is disbanded.

    vehicle: The vehicle that leaves.
    """
    return {
        'kind': 'leave_fleet',
        'vehicle': _id(vehicle, 'vehicle', 'leave_fleet.vehicle'),
    }


def disband_fleet(fleet: Optional[Ref] = None) -> Dict[str, Any]:
    """Every member leaves the fleet and loses its orders; the fleet is gone.

    fleet: The fleet.
    """
    return {
        'kind': 'disband_fleet',
        'fleet': _id(fleet, 'fleet', 'disband_fleet.fleet'),
    }


def set_fleet_options(fleet: Optional[Ref] = None, formation: Ref = 0, strategy: Ref = 0) -> Dict[str, Any]:
    """Sets a fleet's formation and combat strategy.

    fleet: The fleet.
    formation: A formation of the rules view (0 by default).
    strategy: A position in our own strategies (my.strategies).
    """
    return {
        'kind': 'set_fleet_options',
        'fleet': _id(fleet, 'fleet', 'set_fleet_options.fleet'),
        'formation': _index(formation, 'set_fleet_options.formation'),
        'strategy': _index(strategy, 'set_fleet_options.strategy'),
    }


def set_fleet_leader(fleet: Optional[Ref] = None, vehicle: Optional[Ref] = None) -> Dict[str, Any]:
    """Makes one of the fleet's members at its location its leader, the vehicle the formation forms
    around.

    fleet: The fleet.
    vehicle: The new leader.
    """
    return {
        'kind': 'set_fleet_leader',
        'fleet': _id(fleet, 'fleet', 'set_fleet_leader.fleet'),
        'vehicle': _id(vehicle, 'vehicle', 'set_fleet_leader.vehicle'),
    }


def set_vehicle_strategy(design: Optional[Ref] = None, strategy: Ref = 0) -> Dict[str, Any]:
    """Sets the combat strategy every vehicle of one of our designs uses.

    design: The design.
    strategy: A position in our own strategies.
    """
    return {
        'kind': 'set_vehicle_strategy',
        'design': _id(design, 'design', 'set_vehicle_strategy.design'),
        'strategy': _index(strategy, 'set_vehicle_strategy.strategy'),
    }


def rename(vehicle: Optional[Ref] = None, fleet: Optional[Ref] = None, design: Optional[Ref] = None, planet: Optional[Ref] = None, name: str = '') -> Dict[str, Any]:
    """Renames one of our vehicles, fleets, designs or colonies (name one).

    vehicle: A vehicle.
    fleet: Or a fleet.
    design: Or a design.
    planet: Or a colony, by its planet.
    name: The new name.
    """
    return {
        'kind': 'rename',
        'vehicle': _id(vehicle, 'vehicle', 'rename.vehicle'),
        'fleet': _id(fleet, 'fleet', 'rename.fleet'),
        'design': _id(design, 'design', 'rename.design'),
        'planet': _id(planet, 'object', 'rename.planet'),
        'name': _text(name, 'rename.name'),
    }


def scrap(vehicle: Optional[Ref] = None, facility_planet: Optional[Ref] = None, facility_slot: int = -1, move_first: Optional[LocationLike] = None) -> Dict[str, Any]:
    """The Scrap window's Scrap for one vehicle, or Scrap Facilities for one facility of a colony. A
    vehicle is scrapped at once in a turn-based game; in a simultaneous game Scrap becomes its only
    order, carried out when it next acts. With move_first the vehicle first moves to that sector
    (the computer player's way of scrapping at a yard). Scrap Facilities acts at once in both turn
    styles.

    vehicle: The vehicle to scrap.
    facility_planet: Or the colony whose facility goes.
    facility_slot: That facility's position in the colony's list (-1 by default).
    move_first: Where to go before scrapping (no system: stay).
    """
    return {
        'kind': 'scrap',
        'vehicle': _id(vehicle, 'vehicle', 'scrap.vehicle'),
        'facility_planet': _id(facility_planet, 'object', 'scrap.facility_planet'),
        'facility_slot': _int(facility_slot, 'scrap.facility_slot'),
        'move_first': {'system': None, 'x': 6, 'y': 6} if move_first is None else _struct(move_first, 'location', 'scrap.move_first'),
    }


def mothball(vehicle: Optional[Ref] = None, mothball: bool = True) -> Dict[str, Any]:
    """Mothballs a vehicle, or brings it back into service (mothball false). Like Scrap, it acts at
    once in a turn-based game and as the vehicle's only order in a simultaneous one.

    vehicle: The vehicle.
    mothball: True to mothball (the default), false to unmothball.
    """
    return {
        'kind': 'mothball',
        'vehicle': _id(vehicle, 'vehicle', 'mothball.vehicle'),
        'mothball': _bool(mothball, 'mothball.mothball'),
    }


def analyze(vehicle: Optional[Ref] = None) -> Dict[str, Any]:
    """The Scrap window's "Deconstruct & Analyze": the vehicle is taken apart and may teach one
    technology level.

    vehicle: The vehicle.
    """
    return {
        'kind': 'analyze',
        'vehicle': _id(vehicle, 'vehicle', 'analyze.vehicle'),
    }


def self_destruct(vehicle: Optional[Ref] = None) -> Dict[str, Any]:
    """The vehicle destroys itself.

    vehicle: The vehicle.
    """
    return {
        'kind': 'self_destruct',
        'vehicle': _id(vehicle, 'vehicle', 'self_destruct.vehicle'),
    }


def fire_on(vehicle: Optional[Ref] = None) -> Dict[str, Any]:
    """The Scrap window's "Fire On And Destroy": our armed ships in the sector destroy one of our own
    vehicles.

    vehicle: The vehicle to destroy.
    """
    return {
        'kind': 'fire_on',
        'vehicle': _id(vehicle, 'vehicle', 'fire_on.vehicle'),
    }


def retrofit(vehicle: Optional[Ref] = None, design: Optional[Ref] = None) -> Dict[str, Any]:
    """Refits a vehicle to another of our designs at one of our space yards. A Scrap window action like
    scrap.

    vehicle: The vehicle.
    design: The design to refit it to.
    """
    return {
        'kind': 'retrofit',
        'vehicle': _id(vehicle, 'vehicle', 'retrofit.vehicle'),
        'design': _id(design, 'design', 'retrofit.design'),
    }


def set_minister(vehicle: Optional[Ref] = None, planet: Optional[Ref] = None, empire_wide: bool = False, on: bool = True) -> Dict[str, Any]:
    """Puts a vehicle or colony under its minister (the computer controls it), or takes it back;
    empire_wide does the same for everything of ours.

    vehicle: A vehicle.
    planet: Or a colony, by its planet.
    empire_wide: Every vehicle and colony at once.
    on: Minister control on (the default) or off.
    """
    return {
        'kind': 'set_minister',
        'vehicle': _id(vehicle, 'vehicle', 'set_minister.vehicle'),
        'planet': _id(planet, 'object', 'set_minister.planet'),
        'empire_wide': _bool(empire_wide, 'set_minister.empire_wide'),
        'on': _bool(on, 'set_minister.on'),
    }


def enter_sector(vehicle: Optional[Ref] = None, fleet: Optional[Ref] = None, where: Optional[LocationLike] = None, enter: bool = True, tagged: Optional[Sequence[Ref]] = None) -> Dict[str, Any]:
    """Turn-based games: the answer to the question asked when a group's move stops before a sector
    with enemies in it (my.questions in the view). With enter the group carries on into the sector
    and its battle; otherwise the move stops and the order list is cleared. A tagged group's
    question is answered with its vehicles in tagged.

    vehicle: The vehicle asked.
    fleet: Or the fleet.
    where: The sector the question is about.
    enter: Enter (the default) or stay out.
    tagged: A tagged group's vehicles, in tag order.
    """
    return {
        'kind': 'enter_sector',
        'vehicle': _id(vehicle, 'vehicle', 'enter_sector.vehicle'),
        'fleet': _id(fleet, 'fleet', 'enter_sector.fleet'),
        'where': {'system': None, 'x': 6, 'y': 6} if where is None else _struct(where, 'location', 'enter_sector.where'),
        'enter': _bool(enter, 'enter_sector.enter'),
        'tagged': [] if tagged is None else _ids(tagged, 'vehicle', 'enter_sector.tagged'),
    }


def open_vehicle_report(vehicle: Optional[Ref] = None) -> Dict[str, Any]:
    """A human player opened the report of a foreign vehicle: when our scanners reach it, the designs
    the report shows become known. A script AI may give it to learn designs the same way.

    vehicle: The foreign vehicle.
    """
    return {
        'kind': 'open_vehicle_report',
        'vehicle': _id(vehicle, 'vehicle', 'open_vehicle_report.vehicle'),
    }


def queue_add(target: Optional[TargetLike] = None, item: Optional[Dict[str, Any]] = None, position: int = -1) -> Dict[str, Any]:
    """Adds an item to a construction queue: a colony's, or a vehicle's with a space yard.

    target: Whose queue.
    item: What to build.
    position: Where in the queue; -1 (the default) is the end.
    """
    return {
        'kind': 'queue_add',
        'target': {'planet': None, 'vehicle': None} if target is None else _struct(target, 'queue_target', 'queue_add.target'),
        'item': {'kind': 'vehicle', 'design': None, 'facility': 0, 'count': 1, 'spent': {'minerals': 0, 'organics': 0, 'radioactives': 0}} if item is None else _struct(item, 'queue_item', 'queue_add.item'),
        'position': _int(position, 'queue_add.position'),
    }


def queue_remove(target: Optional[TargetLike] = None, index: int = 0) -> Dict[str, Any]:
    """Removes the item at index.

    target: Whose queue.
    index: The item's position.
    """
    return {
        'kind': 'queue_remove',
        'target': {'planet': None, 'vehicle': None} if target is None else _struct(target, 'queue_target', 'queue_remove.target'),
        'index': _int(index, 'queue_remove.index'),
    }


def queue_move(target: Optional[TargetLike] = None, from_index: int = 0, to_index: int = 0) -> Dict[str, Any]:
    """Moves an item within the queue.

    target: Whose queue.
    from_index: Its position now.
    to_index: Its new position.
    """
    return {
        'kind': 'queue_move',
        'target': {'planet': None, 'vehicle': None} if target is None else _struct(target, 'queue_target', 'queue_move.target'),
        'from_index': _int(from_index, 'queue_move.from_index'),
        'to_index': _int(to_index, 'queue_move.to_index'),
    }


def queue_set_count(target: Optional[TargetLike] = None, index: int = 0, count: int = 1) -> Dict[str, Any]:
    """Changes how many of an item are built together.

    target: Whose queue.
    index: The item's position.
    count: The new count (1 by default).
    """
    return {
        'kind': 'queue_set_count',
        'target': {'planet': None, 'vehicle': None} if target is None else _struct(target, 'queue_target', 'queue_set_count.target'),
        'index': _int(index, 'queue_set_count.index'),
        'count': _int(count, 'queue_set_count.count'),
    }


def queue_flags(target: Optional[TargetLike] = None, on_hold: bool = False, repeat: bool = False, emergency: bool = False, auto_waypoint: int = -1) -> Dict[str, Any]:
    """Sets a queue's switches.

    target: Whose queue.
    on_hold: Nothing is built while on hold.
    repeat: A finished item goes on being built.
    emergency: Emergency building: faster for a while, then slower.
    auto_waypoint: New vehicles move to this waypoint slot; -1 (the default) for none.
    """
    return {
        'kind': 'queue_flags',
        'target': {'planet': None, 'vehicle': None} if target is None else _struct(target, 'queue_target', 'queue_flags.target'),
        'on_hold': _bool(on_hold, 'queue_flags.on_hold'),
        'repeat': _bool(repeat, 'queue_flags.repeat'),
        'emergency': _bool(emergency, 'queue_flags.emergency'),
        'auto_waypoint': _int(auto_waypoint, 'queue_flags.auto_waypoint'),
    }


def queue_replace_facility(target: Optional[TargetLike] = None, index: int = 0, facility: Ref = 0) -> Dict[str, Any]:
    """Switches a queued facility, in place, to another facility of the same family that we have
    researched, keeping its count and what was paid into it (the Upgrade Facilities button).

    target: Whose queue.
    index: The item's position.
    facility: The facility to build instead.
    """
    return {
        'kind': 'queue_replace_facility',
        'target': {'planet': None, 'vehicle': None} if target is None else _struct(target, 'queue_target', 'queue_replace_facility.target'),
        'index': _int(index, 'queue_replace_facility.index'),
        'facility': _index(facility, 'queue_replace_facility.facility'),
    }


def set_colony_type(planet: Optional[Ref] = None, colony_type: str = '') -> Dict[str, Any]:
    """Sets a colony's type (one of my.colony_types); also the answer when the game asks for a new
    colony's type.

    planet: The colony's planet.
    colony_type: The type's name.
    """
    return {
        'kind': 'set_colony_type',
        'planet': _id(planet, 'object', 'set_colony_type.planet'),
        'colony_type': _text(colony_type, 'set_colony_type.colony_type'),
    }


def abandon_planet(planet: Optional[Ref] = None) -> Dict[str, Any]:
    """Gives up a colony.

    planet: The colony's planet.
    """
    return {
        'kind': 'abandon_planet',
        'planet': _id(planet, 'object', 'abandon_planet.planet'),
    }


def cloak_colony(planet: Optional[Ref] = None, cloak: bool = True) -> Dict[str, Any]:
    """Cloaks or decloaks a colony, at once and at no cost. Cloaking needs a cloak level of 2 or more
    from the colony's facilities.

    planet: The colony's planet.
    cloak: Cloak (the default) or decloak.
    """
    return {
        'kind': 'cloak_colony',
        'planet': _id(planet, 'object', 'cloak_colony.planet'),
        'cloak': _bool(cloak, 'cloak_colony.cloak'),
    }


def transfer_cargo(from_vehicle: Optional[Ref] = None, from_planet: Optional[Ref] = None, to_vehicle: Optional[Ref] = None, to_planet: Optional[Ref] = None, unit_design: Optional[Ref] = None, population_race: Optional[Ref] = None, amount: int = 0) -> Dict[str, Any]:
    """Moves cargo at once between two of our holders (vehicles or colonies) in the same sector: units
    of one design, or population of one race.

    from_vehicle: The holder it leaves...
    from_planet: ...a vehicle or a colony.
    to_vehicle: The holder it goes to...
    to_planet: ...a vehicle or a colony.
    unit_design: The units' design; null to move population.
    population_race: The race of the population moved (the empire it belongs to).
    amount: Units, or millions of population.
    """
    return {
        'kind': 'transfer_cargo',
        'from_vehicle': _id(from_vehicle, 'vehicle', 'transfer_cargo.from_vehicle'),
        'from_planet': _id(from_planet, 'object', 'transfer_cargo.from_planet'),
        'to_vehicle': _id(to_vehicle, 'vehicle', 'transfer_cargo.to_vehicle'),
        'to_planet': _id(to_planet, 'object', 'transfer_cargo.to_planet'),
        'unit_design': _id(unit_design, 'design', 'transfer_cargo.unit_design'),
        'population_race': _id(population_race, 'empire', 'transfer_cargo.population_race'),
        'amount': _int(amount, 'transfer_cargo.amount'),
    }


def jettison_cargo(vehicle: Optional[Ref] = None, planet: Optional[Ref] = None, population: Optional[Sequence[Dict[str, Any]]] = None, units: Optional[Sequence[Dict[str, Any]]] = None) -> Dict[str, Any]:
    """Throws cargo away at once, from one of our ships or bases or from a colony's stored cargo (never
    its own population). Each unit thrown away counts as lost.

    vehicle: The vehicle...
    planet: ...or the colony.
    population: Millions of each race to throw away.
    units: Units of each design to throw away.
    """
    return {
        'kind': 'jettison_cargo',
        'vehicle': _id(vehicle, 'vehicle', 'jettison_cargo.vehicle'),
        'planet': _id(planet, 'object', 'jettison_cargo.planet'),
        'population': [] if population is None else _structs(population, 'population_group', 'jettison_cargo.population'),
        'units': [] if units is None else _structs(units, 'unit_stack', 'jettison_cargo.units'),
    }


def create_design(design: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    """Adds a design. The engine gives it its id and owner and checks it as the designer does
    (design_figures in view.md tells in advance whether it is legal and why not).

    design: The design: name, type, hull and components matter.
    """
    return {
        'kind': 'create_design',
        'design': {'id': None, 'owner': None, 'name': '', 'design_type': '', 'hull': 0, 'entries': [], 'strategy': 0, 'obsolete': False, 'created_turn': 0, 'template_name': '', 'retrofitted': False, 'ever_built': False, 'built': 0, 'lost': 0, 'enemy_tonnage_destroyed': 0, 'scrapped': 0} if design is None else _struct(design, 'design', 'create_design.design'),
    }


def edit_design(design: Optional[Ref] = None, new_design: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    """Changes one of our designs in place; refused for a design that was built, retrofitted to, or is
    in a queue.

    design: The design to change.
    new_design: Its new contents.
    """
    return {
        'kind': 'edit_design',
        'design': _id(design, 'design', 'edit_design.design'),
        'new_design': {'id': None, 'owner': None, 'name': '', 'design_type': '', 'hull': 0, 'entries': [], 'strategy': 0, 'obsolete': False, 'created_turn': 0, 'template_name': '', 'retrofitted': False, 'ever_built': False, 'built': 0, 'lost': 0, 'enemy_tonnage_destroyed': 0, 'scrapped': 0} if new_design is None else _struct(new_design, 'design', 'edit_design.new_design'),
    }


def set_design_obsolete(design: Optional[Ref] = None, obsolete: bool = True) -> Dict[str, Any]:
    """Marks a design obsolete, or current again.

    design: The design.
    obsolete: Obsolete (the default) or not.
    """
    return {
        'kind': 'set_design_obsolete',
        'design': _id(design, 'design', 'set_design_obsolete.design'),
        'obsolete': _bool(obsolete, 'set_design_obsolete.obsolete'),
    }


def delete_design(design: Optional[Ref] = None) -> Dict[str, Any]:
    """Deletes a design that was never built.

    design: The design.
    """
    return {
        'kind': 'delete_design',
        'design': _id(design, 'design', 'delete_design.design'),
    }


def set_research(queue: Optional[Sequence[Dict[str, Any]]] = None, evenly: bool = True, repeat: bool = False) -> Dict[str, Any]:
    """Replaces the research queue (at most 12 projects, one per tech area). A tech area keeps its
    progress while it stays in the queue.

    queue: The projects, in order.
    evenly: Share points evenly (the default), or fill the projects in order.
    repeat: A finished area goes back to the end of the queue.
    """
    return {
        'kind': 'set_research',
        'queue': [] if queue is None else _structs(queue, 'research_project', 'set_research.queue'),
        'evenly': _bool(evenly, 'set_research.evenly'),
        'repeat': _bool(repeat, 'set_research.repeat'),
    }


def set_intel(queue: Optional[Sequence[Dict[str, Any]]] = None, evenly: bool = True, repeat: bool = False) -> Dict[str, Any]:
    """Replaces the intelligence queue.

    queue: The projects, in order.
    evenly: Share points evenly (the default), or in order.
    repeat: A finished project starts again.
    """
    return {
        'kind': 'set_intel',
        'queue': [] if queue is None else _structs(queue, 'intel_project_order', 'set_intel.queue'),
        'evenly': _bool(evenly, 'set_intel.evenly'),
        'repeat': _bool(repeat, 'set_intel.repeat'),
    }


def send_message(message: Optional[Dict[str, Any]] = None, minister: bool = False) -> Dict[str, Any]:
    """Sends a diplomatic message. The engine gives it its id, sender and date. minister marks a
    message the computer player or a Politics minister writes, whose requests about a third empire
    are not checked as a player's are.

    message: The message.
    minister: Written by a minister.
    """
    return {
        'kind': 'send_message',
        'message': {'id': None, 'from_empire': None, 'to_empire': None, 'sent_turn': 0, 'type': 'general', 'tone': 1, 'text': '', 'treaty': 'none', 'offer': [], 'request': [], 'third_empire': None, 'system': None, 'planet': None, 'in_reply_to': None, 'delivered': False, 'answered': False, 'dated': 0} if message is None else _struct(message, 'message', 'send_message.message'),
        'minister': _bool(minister, 'send_message.minister'),
    }


def answer_message(message: Optional[Ref] = None, accept: bool = False, text: str = '') -> Dict[str, Any]:
    """Answers a message delivered to us: accept or refuse, with a text.

    message: The message answered.
    accept: Accept (false by default: refuse).
    text: The reply's text.
    """
    return {
        'kind': 'answer_message',
        'message': _id(message, 'message', 'answer_message.message'),
        'accept': _bool(accept, 'answer_message.accept'),
        'text': _text(text, 'answer_message.text'),
    }


def decide_war(target: Optional[Ref] = None) -> Dict[str, Any]:
    """A computer player's decision to go to war without a declaration (its speech list was empty): its
    anger toward the empire becomes 100; no treaty changes and no message is sent.

    target: The empire.
    """
    return {
        'kind': 'decide_war',
        'target': _id(target, 'empire', 'decide_war.target'),
    }


def carry_out_demand(demand: Optional[Ref] = None) -> Dict[str, Any]:
    """The Politics minister carries out a demand or request it accepted (leaving a system, declaring
    war on a third empire, stopping espionage, ...).

    demand: The demand, delivered to us.
    """
    return {
        'kind': 'carry_out_demand',
        'demand': _id(demand, 'message', 'carry_out_demand.demand'),
    }


def use_demand_entry(list: str = 'war', about: Optional[Ref] = None) -> Dict[str, Any]:
    """The Politics minister used up one entry of a demand list naming an empire.

    list: Which list.
    about: The empire the entry names.
    """
    return {
        'kind': 'use_demand_entry',
        'list': _enum(list, enums.DEMAND_LIST, 'use_demand_entry.list'),
        'about': _id(about, 'empire', 'use_demand_entry.about'),
    }


def set_waypoint(slot: int = 0, waypoint: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    """Sets or clears one of the ten waypoints.

    slot: 0 to 9.
    waypoint: The waypoint; null clears the slot.
    """
    return {
        'kind': 'set_waypoint',
        'slot': _int(slot, 'set_waypoint.slot'),
        'waypoint': _struct(waypoint, 'waypoint', 'set_waypoint.waypoint', True),
    }


def set_system_flags(system: Optional[Ref] = None, avoid: Optional[bool] = None, claim: Optional[bool] = None) -> Dict[str, Any]:
    """Marks a system to avoid, or claims it; a null field is left as it is.

    system: The system.
    avoid: Among the systems to avoid.
    claim: Among our claimed systems.
    """
    return {
        'kind': 'set_system_flags',
        'system': _id(system, 'system', 'set_system_flags.system'),
        'avoid': _bool(avoid, 'set_system_flags.avoid', True),
        'claim': _bool(claim, 'set_system_flags.claim', True),
    }


def set_system_note(system: Optional[Ref] = None, note: str = '') -> Dict[str, Any]:
    """Writes our note on a system.

    system: The system.
    note: The note; empty to clear it.
    """
    return {
        'kind': 'set_system_note',
        'system': _id(system, 'system', 'set_system_note.system'),
        'note': _text(note, 'set_system_note.note'),
    }


def tag_minefield(location: Optional[LocationLike] = None, tagged: bool = True) -> Dict[str, Any]:
    """Tags a sector as a minefield to route around, or untags it.

    location: The sector.
    tagged: Tag (the default) or untag.
    """
    return {
        'kind': 'tag_minefield',
        'location': {'system': None, 'x': 6, 'y': 6} if location is None else _struct(location, 'location', 'tag_minefield.location'),
        'tagged': _bool(tagged, 'tag_minefield.tagged'),
    }


def set_strategy(index: int = -1, strategy: Optional[Dict[str, Any]] = None, remove: bool = False) -> Dict[str, Any]:
    """Adds, replaces or removes one of our combat strategies.

    index: The strategy's position; -1 (the default) adds a new one.
    strategy: Its name and settings.
    remove: Remove the strategy at index instead.
    """
    return {
        'kind': 'set_strategy',
        'index': _int(index, 'set_strategy.index'),
        'strategy': {'name': '', 'settings': []} if strategy is None else _struct(strategy, 'strategy', 'set_strategy.strategy'),
        'remove': _bool(remove, 'set_strategy.remove'),
    }


def set_repair_priorities(priorities: Optional[Sequence[str]] = None) -> Dict[str, Any]:
    """Replaces the order in which repairs are made.

    priorities: The priorities, first first.
    """
    return {
        'kind': 'set_repair_priorities',
        'priorities': [] if priorities is None else _list_of_text(priorities, 'set_repair_priorities.priorities'),
    }


def set_design_types(design_types: Optional[Sequence[str]] = None) -> Dict[str, Any]:
    """Replaces our list of design types.

    design_types: The types.
    """
    return {
        'kind': 'set_design_types',
        'design_types': [] if design_types is None else _list_of_text(design_types, 'set_design_types.design_types'),
    }


def set_colony_types(colony_types: Optional[Sequence[str]] = None) -> Dict[str, Any]:
    """Replaces our list of colony types.

    colony_types: The types.
    """
    return {
        'kind': 'set_colony_types',
        'colony_types': [] if colony_types is None else _list_of_text(colony_types, 'set_colony_types.colony_types'),
    }


def set_empire_options(ai_minimal_changes: Optional[bool] = None, password_hash: Optional[str] = None, choose_colony_type: Optional[bool] = None) -> Dict[str, Any]:
    """Empire options; a null field is left as it is.

    ai_minimal_changes: The computer player changes as little as it can.
    password_hash: The empire's password, hashed.
    choose_colony_type: Ask for a new colony's type (turn-based games).
    """
    return {
        'kind': 'set_empire_options',
        'ai_minimal_changes': _bool(ai_minimal_changes, 'set_empire_options.ai_minimal_changes', True),
        'password_hash': _text(password_hash, 'set_empire_options.password_hash', True),
        'choose_colony_type': _bool(choose_colony_type, 'set_empire_options.choose_colony_type', True),
    }


def set_email(email: str = '') -> Dict[str, Any]:
    """Changes the empire's e-mail address.

    email: The address.
    """
    return {
        'kind': 'set_email',
        'email': _text(email, 'set_email.email'),
    }


def set_ministers(areas: Optional[Sequence[str]] = None, style: Optional[str] = None, use_race_style: Optional[bool] = None, new_vehicles: Optional[bool] = None, individual: Optional[bool] = None, fleets: Optional[bool] = None, complete_ai: Optional[bool] = None) -> Dict[str, Any]:
    """The Ministers window; a null field is left as it is.

    areas: The minister areas switched on.
    style: The minister style: a folder of AI files, empty for the race's own.
    use_race_style: Use the race's own files even with a style.
    new_vehicles: New vehicles start under minister control.
    individual: Minister control of every vehicle, fleet and colony, on or off.
    fleets: Minister control of every fleet, on or off.
    complete_ai: Everything above at once, on or off.
    """
    return {
        'kind': 'set_ministers',
        'areas': _enums(areas, enums.MINISTER, 'set_ministers.areas', True),
        'style': _text(style, 'set_ministers.style', True),
        'use_race_style': _bool(use_race_style, 'set_ministers.use_race_style', True),
        'new_vehicles': _bool(new_vehicles, 'set_ministers.new_vehicles', True),
        'individual': _bool(individual, 'set_ministers.individual', True),
        'fleets': _bool(fleets, 'set_ministers.fleets', True),
        'complete_ai': _bool(complete_ai, 'set_ministers.complete_ai', True),
    }


def set_encounter_options(clear_orders_on_encounter: Optional[str] = None, avoid_tagged_minefields: Optional[bool] = None, avoid_restricted_systems: Optional[bool] = None) -> Dict[str, Any]:
    """The empire's Ship Movement and Ship Orders options; a null field is left as it is.

    clear_orders_on_encounter: Whom meeting after a warp clears a group's orders.
    avoid_tagged_minefields: Routes go around tagged minefields.
    avoid_restricted_systems: Routes never cross the systems to avoid.
    """
    return {
        'kind': 'set_encounter_options',
        'clear_orders_on_encounter': _enum(clear_orders_on_encounter, enums.ENCOUNTER_CLEAR, 'set_encounter_options.clear_orders_on_encounter', True),
        'avoid_tagged_minefields': _bool(avoid_tagged_minefields, 'set_encounter_options.avoid_tagged_minefields', True),
        'avoid_restricted_systems': _bool(avoid_restricted_systems, 'set_encounter_options.avoid_restricted_systems', True),
    }


def set_interface_options(options: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    """Replaces the Empire Options switches and what the windows remember. Only auto_claim_colonized
    changes the game; the rest is for the client.

    options: Every switch.
    """
    return {
        'kind': 'set_interface_options',
        'options': {'show_log_at_turn_start': True, 'confirm_end_turn': True, 'confirm_scrap': True, 'confirm_stellar_manipulation': True, 'confirm_delete_research': True, 'confirm_delete_intel': True, 'confirm_delete_first_queue_item': True, 'note_similar_abilities': True, 'skip_under_construction': False, 'skip_damaged': False, 'stop_once_per_location': False, 'skip_in_fleets': False, 'warp_point_names': True, 'planet_names': False, 'colonizable_markers': True, 'system_grid': False, 'coordinate_location': True, 'facility_markers': 0, 'galaxy_grid_lines': True, 'galaxy_warp_lines': True, 'latest_construction_only': False, 'latest_components_only': False, 'auto_claim_colonized': True, 'log_filter': 0, 'log_position': 0, 'log_scroll': 0, 'planets_tab': 0, 'planets_no_sys_to_avoid': False, 'queues_tab': 0, 'queues_shown': 15, 'simulator_no_obsolete': False, 'ships_tab': 0, 'ships_shown': 7, 'planets_sort': [0, 0, 0, 0, 0], 'colonies_sort': [0, 0, 0, 0, 0], 'ships_sort': [0, 0, 0, 0, 0], 'queues_sort': [0, 0, 0, 0, 0], 'replay_animate': True, 'replay_fast': False, 'replay_view_rect': True, 'replay_grid': False, 'design_to_hit': False, 'design_condensed': False, 'designs_hide_obsolete': False, 'designs_stats_view': False} if options is None else _struct(options, 'interface_options', 'set_interface_options.options'),
    }


# ---- Types the commands carry --------------------------------------------------------------

def square(x: int = 0, y: int = 0) -> Dict[str, Any]:
    """A square (docs/sdk/commands.md).

    x: Column.
    y: Row.
    """
    return {
        'x': _int(x, 'square.x'),
        'y': _int(y, 'square.y'),
    }


def location(system: Optional[Ref] = None, x: int = 6, y: int = 6) -> Dict[str, Any]:
    """A sector of a system.

    system: The system (null: no place).
    x: Column, 0 to 12 left to right (6 by default).
    y: Row, 0 to 12 top to bottom; (6, 6) is the centre (6 by default).
    """
    return {
        'system': _id(system, 'system', 'location.system'),
        'x': _int(x, 'location.x'),
        'y': _int(y, 'location.y'),
    }


def sector(x: int = 6, y: int = 6) -> Dict[str, Any]:
    """A sector within a system.

    x: Column, 0 to 12 (6 by default).
    y: Row, 0 to 12 (6 by default).
    """
    return {
        'x': _int(x, 'sector.x'),
        'y': _int(y, 'sector.y'),
    }


def resources(minerals: int = 0, organics: int = 0, radioactives: int = 0) -> Dict[str, Any]:
    """A resources (docs/sdk/commands.md).

    minerals: Minerals.
    organics: Organics.
    radioactives: Radioactives.
    """
    return {
        'minerals': _int(minerals, 'resources.minerals'),
        'organics': _int(organics, 'resources.organics'),
        'radioactives': _int(radioactives, 'resources.radioactives'),
    }


def queue_target(planet: Optional[Ref] = None, vehicle: Optional[Ref] = None) -> Dict[str, Any]:
    """A construction queue: a colony's (by its planet) or a vehicle's with a space yard. Name one.

    planet: The colony's planet.
    vehicle: Or the vehicle.
    """
    return {
        'planet': _id(planet, 'object', 'queue_target.planet'),
        'vehicle': _id(vehicle, 'vehicle', 'queue_target.vehicle'),
    }


def queue_item(kind: str = 'vehicle', design: Optional[Ref] = None, facility: Ref = 0, count: int = 1, spent: Optional[ResourcesLike] = None) -> Dict[str, Any]:
    """A queue_item (docs/sdk/commands.md).

    kind: A vehicle (or units), a facility, or a facility upgrade.
    design: The design built (vehicles).
    facility: The facility built, or the upgrade's target (0 by default).
    count: How many are built together (1 by default); an upgrade's count is fixed when it is
        queued.
    spent: What was paid into it so far (the engine keeps this; leave it out).
    """
    return {
        'kind': _enum(kind, enums.QUEUE_ITEM_KIND, 'queue_item.kind'),
        'design': _id(design, 'design', 'queue_item.design'),
        'facility': _index(facility, 'queue_item.facility'),
        'count': _int(count, 'queue_item.count'),
        'spent': {'minerals': 0, 'organics': 0, 'radioactives': 0} if spent is None else _struct(spent, 'resources', 'queue_item.spent'),
    }


def design(id: Optional[Ref] = None, owner: Optional[Ref] = None, name: str = '', design_type: str = '', hull: Ref = 0, entries: Optional[Sequence[Dict[str, Any]]] = None, strategy: Ref = 0, obsolete: bool = False, created_turn: int = 0, template_name: str = '', retrofitted: bool = False, ever_built: bool = False, built: int = 0, lost: int = 0, enemy_tonnage_destroyed: int = 0, scrapped: int = 0) -> Dict[str, Any]:
    """A design as create_design and edit_design take it. Only name, design_type, hull, entries and
    strategy matter there; the engine sets the rest.

    id: Its id (set by the engine).
    owner: Its owner (set by the engine).
    name: Its name, unique in the game.
    design_type: One of my.design_types.
    hull: The hull.
    entries: The components, in order.
    strategy: The combat strategy its vehicles use (a position in our strategies).
    obsolete: Obsolete.
    created_turn: When it was made.
    template_name: The computer designer's template it came from.
    retrofitted: A ship was refitted to it.
    ever_built: One was ever built.
    built: Vehicles built.
    lost: Vehicles lost.
    enemy_tonnage_destroyed: Tonnage of enemies its vehicles destroyed.
    scrapped: Vehicles scrapped.
    """
    return {
        'id': _id(id, 'design', 'design.id'),
        'owner': _id(owner, 'empire', 'design.owner'),
        'name': _text(name, 'design.name'),
        'design_type': _text(design_type, 'design.design_type'),
        'hull': _index(hull, 'design.hull'),
        'entries': [] if entries is None else _structs(entries, 'design_entry', 'design.entries'),
        'strategy': _index(strategy, 'design.strategy'),
        'obsolete': _bool(obsolete, 'design.obsolete'),
        'created_turn': _int(created_turn, 'design.created_turn'),
        'template_name': _text(template_name, 'design.template_name'),
        'retrofitted': _bool(retrofitted, 'design.retrofitted'),
        'ever_built': _bool(ever_built, 'design.ever_built'),
        'built': _int(built, 'design.built'),
        'lost': _int(lost, 'design.lost'),
        'enemy_tonnage_destroyed': _int(enemy_tonnage_destroyed, 'design.enemy_tonnage_destroyed'),
        'scrapped': _int(scrapped, 'design.scrapped'),
    }


def design_entry(component: Ref = 0, mount: int = -1) -> Dict[str, Any]:
    """A design_entry (docs/sdk/commands.md).

    component: The component.
    mount: A weapon mount of the rules view, or -1 (the default) for none.
    """
    return {
        'component': _index(component, 'design_entry.component'),
        'mount': _int(mount, 'design_entry.mount'),
    }


def research_project(area: Optional[Ref] = None, progress: int = 0) -> Dict[str, Any]:
    """A research_project (docs/sdk/commands.md).

    area: The tech area.
    progress: Points toward its next level (the engine keeps it).
    """
    return {
        'area': _index(area, 'research_project.area', True),
        'progress': _int(progress, 'research_project.progress'),
    }


def intel_project_order(project: Ref = 0, target: Optional[Ref] = None, target_planet: Optional[Ref] = None, target_vehicle: Optional[Ref] = None, third_empire: Optional[Ref] = None, target_tech: Optional[Ref] = None, progress: int = 0) -> Dict[str, Any]:
    """A intel_project_order (docs/sdk/commands.md).

    project: The project.
    target: The empire it is aimed at (none for defense).
    target_planet: A planet it aims at; null for any.
    target_vehicle: A vehicle it aims at.
    third_empire: The other empire of a political operation.
    target_tech: The area a theft aims at; null for any.
    progress: Points so far (the engine keeps it).
    """
    return {
        'project': _index(project, 'intel_project_order.project'),
        'target': _id(target, 'empire', 'intel_project_order.target'),
        'target_planet': _ref(target_planet, 'object', 'intel_project_order.target_planet'),
        'target_vehicle': _ref(target_vehicle, 'vehicle', 'intel_project_order.target_vehicle'),
        'third_empire': _id(third_empire, 'empire', 'intel_project_order.third_empire'),
        'target_tech': _index(target_tech, 'intel_project_order.target_tech', True),
        'progress': _int(progress, 'intel_project_order.progress'),
    }


def message(id: Optional[Ref] = None, from_empire: Optional[Ref] = None, to_empire: Optional[Ref] = None, sent_turn: int = 0, type: str = 'general', tone: int = 1, text: str = '', treaty: str = 'none', offer: Optional[Sequence[Dict[str, Any]]] = None, request: Optional[Sequence[Dict[str, Any]]] = None, third_empire: Optional[Ref] = None, system: Optional[Ref] = None, planet: Optional[Ref] = None, in_reply_to: Optional[Ref] = None, delivered: bool = False, answered: bool = False, dated: int = 0) -> Dict[str, Any]:
    """A diplomatic message: what send_message sends and the view's messages hold.

    id: Its id (set by the engine).
    from_empire: The sender (set by the engine).
    to_empire: The recipient.
    sent_turn: When it was sent.
    type: What kind of message.
    tone: 0 pleading, 1 neutral (the default), 2 demanding.
    text: What it says.
    treaty: The treaty proposed, accepted or broken (none by default).
    offer: What the sender gives.
    request: What the sender asks for.
    third_empire: The empire a request is about.
    system: The system a demand or request names.
    planet: The planet a demand or request names.
    in_reply_to: The message it answers.
    delivered: It reached the recipient.
    answered: It was answered.
    dated: The turn of its entry in the recipient's log.
    """
    return {
        'id': _id(id, 'message', 'message.id'),
        'from_empire': _id(from_empire, 'empire', 'message.from_empire'),
        'to_empire': _id(to_empire, 'empire', 'message.to_empire'),
        'sent_turn': _int(sent_turn, 'message.sent_turn'),
        'type': _enum(type, enums.MESSAGE_TYPE, 'message.type'),
        'tone': _int(tone, 'message.tone'),
        'text': _text(text, 'message.text'),
        'treaty': _enum(treaty, enums.TREATY, 'message.treaty'),
        'offer': [] if offer is None else _structs(offer, 'package_item', 'message.offer'),
        'request': [] if request is None else _structs(request, 'package_item', 'message.request'),
        'third_empire': _id(third_empire, 'empire', 'message.third_empire'),
        'system': _id(system, 'system', 'message.system'),
        'planet': _ref(planet, 'object', 'message.planet'),
        'in_reply_to': _ref(in_reply_to, 'message', 'message.in_reply_to'),
        'delivered': _bool(delivered, 'message.delivered'),
        'answered': _bool(answered, 'message.answered'),
        'dated': _int(dated, 'message.dated'),
    }


def package_item(kind: str = 'resources', resources: Optional[ResourcesLike] = None, tech: Optional[Ref] = None, planet: Optional[Ref] = None, vehicle: Optional[Ref] = None, system: Optional[Ref] = None, treaty: str = 'none', empire: Optional[Ref] = None) -> Dict[str, Any]:
    """One thing given or asked for in a trade, gift or tribute.

    kind: What it is.
    resources: Resources.
    tech: A tech area (null: any).
    planet: A planet.
    vehicle: A vehicle.
    system: A system.
    treaty: A treaty (none by default).
    empire: The empire of a communication channel.
    """
    return {
        'kind': _enum(kind, enums.PACKAGE_ITEM_KIND, 'package_item.kind'),
        'resources': {'minerals': 0, 'organics': 0, 'radioactives': 0} if resources is None else _struct(resources, 'resources', 'package_item.resources'),
        'tech': _index(tech, 'package_item.tech', True),
        'planet': _ref(planet, 'object', 'package_item.planet'),
        'vehicle': _ref(vehicle, 'vehicle', 'package_item.vehicle'),
        'system': _id(system, 'system', 'package_item.system'),
        'treaty': _enum(treaty, enums.TREATY, 'package_item.treaty'),
        'empire': _id(empire, 'empire', 'package_item.empire'),
    }


def waypoint(name: str = '', location: Optional[LocationLike] = None, set: bool = False) -> Dict[str, Any]:
    """A waypoint (docs/sdk/commands.md).

    name: Its name.
    location: Where it is.
    set: The slot holds a waypoint.
    """
    return {
        'name': _text(name, 'waypoint.name'),
        'location': {'system': None, 'x': 6, 'y': 6} if location is None else _struct(location, 'location', 'waypoint.location'),
        'set': _bool(set, 'waypoint.set'),
    }


def strategy(name: str = '', settings: Optional[Sequence[Dict[str, Any]]] = None) -> Dict[str, Any]:
    """A combat strategy: its name and its settings, as the classic data writes them.

    name: Its name.
    settings: Its settings, in order.
    """
    return {
        'name': _text(name, 'strategy.name'),
        'settings': [] if settings is None else _structs(settings, 'strategy_setting', 'strategy.settings'),
    }


def strategy_setting(name: str = '', value: str = '') -> Dict[str, Any]:
    """A strategy_setting (docs/sdk/commands.md).

    name: The setting's name, as the data files write it.
    value: Its value, as written.
    """
    return {
        'name': _text(name, 'strategy_setting.name'),
        'value': _text(value, 'strategy_setting.value'),
    }


def population_group(race: Optional[Ref] = None, millions: int = 0) -> Dict[str, Any]:
    """A population_group (docs/sdk/commands.md).

    race: The empire whose race it is.
    millions: Millions of people.
    """
    return {
        'race': _id(race, 'empire', 'population_group.race'),
        'millions': _int(millions, 'population_group.millions'),
    }


def unit_stack(design: Optional[Ref] = None, count: int = 0) -> Dict[str, Any]:
    """A unit_stack (docs/sdk/commands.md).

    design: The units' design.
    count: How many.
    """
    return {
        'design': _id(design, 'design', 'unit_stack.design'),
        'count': _int(count, 'unit_stack.count'),
    }


def interface_options(show_log_at_turn_start: bool = True, confirm_end_turn: bool = True, confirm_scrap: bool = True, confirm_stellar_manipulation: bool = True, confirm_delete_research: bool = True, confirm_delete_intel: bool = True, confirm_delete_first_queue_item: bool = True, note_similar_abilities: bool = True, skip_under_construction: bool = False, skip_damaged: bool = False, stop_once_per_location: bool = False, skip_in_fleets: bool = False, warp_point_names: bool = True, planet_names: bool = False, colonizable_markers: bool = True, system_grid: bool = False, coordinate_location: bool = True, facility_markers: int = 0, galaxy_grid_lines: bool = True, galaxy_warp_lines: bool = True, latest_construction_only: bool = False, latest_components_only: bool = False, auto_claim_colonized: bool = True, log_filter: int = 0, log_position: int = 0, log_scroll: int = 0, planets_tab: int = 0, planets_no_sys_to_avoid: bool = False, queues_tab: int = 0, queues_shown: int = 15, simulator_no_obsolete: bool = False, ships_tab: int = 0, ships_shown: int = 7, planets_sort: Optional[Sequence[int]] = None, colonies_sort: Optional[Sequence[int]] = None, ships_sort: Optional[Sequence[int]] = None, queues_sort: Optional[Sequence[int]] = None, replay_animate: bool = True, replay_fast: bool = False, replay_view_rect: bool = True, replay_grid: bool = False, design_to_hit: bool = False, design_condensed: bool = False, designs_hide_obsolete: bool = False, designs_stats_view: bool = False) -> Dict[str, Any]:
    """The Empire Options switches and what the windows remember. Only auto_claim_colonized changes the
    game. Sort keys are five column numbers plus one, newest first, 0 for none.

    show_log_at_turn_start: Open the log when a turn starts (true by default).
    confirm_end_turn: Ask before ending the turn (true by default).
    confirm_scrap: Ask before scrapping (true by default).
    confirm_stellar_manipulation: Ask before a stellar manipulation (true by default).
    confirm_delete_research: Ask before removing research (true by default).
    confirm_delete_intel: Ask before removing intelligence projects (true by default).
    confirm_delete_first_queue_item: Ask before removing the item being built (true by default).
    note_similar_abilities: Note similar abilities in reports (true by default).
    skip_under_construction: Next and Previous skip vehicles being built.
    skip_damaged: ... skip damaged vehicles.
    stop_once_per_location: ... stop once per place.
    skip_in_fleets: ... skip fleet members.
    warp_point_names: System map: warp point names (true by default).
    planet_names: System map: planet names.
    colonizable_markers: System map: colonizable markers (true by default).
    system_grid: System map: the grid.
    coordinate_location: System map: coordinates (true by default).
    facility_markers: Facility marker groups shown (bit i: group i).
    galaxy_grid_lines: Galaxy map: grid lines (true by default).
    galaxy_warp_lines: Galaxy map: warp lines (true by default).
    latest_construction_only: Construction lists: only the latest items.
    latest_components_only: Designer: only the latest components.
    auto_claim_colonized: A system we colonize is claimed (true by default).
    log_filter: The log's filter (0 all, else a category + 1).
    log_position: The selected log entry.
    log_scroll: The log's scroll position.
    planets_tab: The Planets window's tab.
    planets_no_sys_to_avoid: The Planets window hides systems to avoid.
    queues_tab: The Construction Queues window's tab.
    queues_shown: Its toggles (bits; 15 by default).
    simulator_no_obsolete: The combat simulator hides obsolete designs.
    ships_tab: The Ships window's tab.
    ships_shown: Its Show Ships, Units and Fleets toggles (bits; 7 by default).
    planets_sort: The Planets window's sort keys (five; [0, 0, 0, 0, 0] by default).
    colonies_sort: The Colonies window's sort keys (five; [0, 0, 0, 0, 0] by default).
    ships_sort: The Ships window's sort keys (five; [0, 0, 0, 0, 0] by default).
    queues_sort: The Construction Queues window's sort keys (five; [0, 0, 0, 0, 0] by default).
    replay_animate: Combat replays: animate (true by default).
    replay_fast: Combat replays: fast.
    replay_view_rect: Combat replays: the view rectangle (true by default).
    replay_grid: Combat replays: the grid.
    design_to_hit: The designer shows to-hit modifiers.
    design_condensed: The designer's condensed view.
    designs_hide_obsolete: The Designs window hides obsolete designs.
    designs_stats_view: The Designs window shows statistics.
    """
    return {
        'show_log_at_turn_start': _bool(show_log_at_turn_start, 'interface_options.show_log_at_turn_start'),
        'confirm_end_turn': _bool(confirm_end_turn, 'interface_options.confirm_end_turn'),
        'confirm_scrap': _bool(confirm_scrap, 'interface_options.confirm_scrap'),
        'confirm_stellar_manipulation': _bool(confirm_stellar_manipulation, 'interface_options.confirm_stellar_manipulation'),
        'confirm_delete_research': _bool(confirm_delete_research, 'interface_options.confirm_delete_research'),
        'confirm_delete_intel': _bool(confirm_delete_intel, 'interface_options.confirm_delete_intel'),
        'confirm_delete_first_queue_item': _bool(confirm_delete_first_queue_item, 'interface_options.confirm_delete_first_queue_item'),
        'note_similar_abilities': _bool(note_similar_abilities, 'interface_options.note_similar_abilities'),
        'skip_under_construction': _bool(skip_under_construction, 'interface_options.skip_under_construction'),
        'skip_damaged': _bool(skip_damaged, 'interface_options.skip_damaged'),
        'stop_once_per_location': _bool(stop_once_per_location, 'interface_options.stop_once_per_location'),
        'skip_in_fleets': _bool(skip_in_fleets, 'interface_options.skip_in_fleets'),
        'warp_point_names': _bool(warp_point_names, 'interface_options.warp_point_names'),
        'planet_names': _bool(planet_names, 'interface_options.planet_names'),
        'colonizable_markers': _bool(colonizable_markers, 'interface_options.colonizable_markers'),
        'system_grid': _bool(system_grid, 'interface_options.system_grid'),
        'coordinate_location': _bool(coordinate_location, 'interface_options.coordinate_location'),
        'facility_markers': _int(facility_markers, 'interface_options.facility_markers'),
        'galaxy_grid_lines': _bool(galaxy_grid_lines, 'interface_options.galaxy_grid_lines'),
        'galaxy_warp_lines': _bool(galaxy_warp_lines, 'interface_options.galaxy_warp_lines'),
        'latest_construction_only': _bool(latest_construction_only, 'interface_options.latest_construction_only'),
        'latest_components_only': _bool(latest_components_only, 'interface_options.latest_components_only'),
        'auto_claim_colonized': _bool(auto_claim_colonized, 'interface_options.auto_claim_colonized'),
        'log_filter': _int(log_filter, 'interface_options.log_filter'),
        'log_position': _int(log_position, 'interface_options.log_position'),
        'log_scroll': _int(log_scroll, 'interface_options.log_scroll'),
        'planets_tab': _int(planets_tab, 'interface_options.planets_tab'),
        'planets_no_sys_to_avoid': _bool(planets_no_sys_to_avoid, 'interface_options.planets_no_sys_to_avoid'),
        'queues_tab': _int(queues_tab, 'interface_options.queues_tab'),
        'queues_shown': _int(queues_shown, 'interface_options.queues_shown'),
        'simulator_no_obsolete': _bool(simulator_no_obsolete, 'interface_options.simulator_no_obsolete'),
        'ships_tab': _int(ships_tab, 'interface_options.ships_tab'),
        'ships_shown': _int(ships_shown, 'interface_options.ships_shown'),
        'planets_sort': [0, 0, 0, 0, 0] if planets_sort is None else _list_of_int(planets_sort, 'interface_options.planets_sort'),
        'colonies_sort': [0, 0, 0, 0, 0] if colonies_sort is None else _list_of_int(colonies_sort, 'interface_options.colonies_sort'),
        'ships_sort': [0, 0, 0, 0, 0] if ships_sort is None else _list_of_int(ships_sort, 'interface_options.ships_sort'),
        'queues_sort': [0, 0, 0, 0, 0] if queues_sort is None else _list_of_int(queues_sort, 'interface_options.queues_sort'),
        'replay_animate': _bool(replay_animate, 'interface_options.replay_animate'),
        'replay_fast': _bool(replay_fast, 'interface_options.replay_fast'),
        'replay_view_rect': _bool(replay_view_rect, 'interface_options.replay_view_rect'),
        'replay_grid': _bool(replay_grid, 'interface_options.replay_grid'),
        'design_to_hit': _bool(design_to_hit, 'interface_options.design_to_hit'),
        'design_condensed': _bool(design_condensed, 'interface_options.design_condensed'),
        'designs_hide_obsolete': _bool(designs_hide_obsolete, 'interface_options.designs_hide_obsolete'),
        'designs_stats_view': _bool(designs_stats_view, 'interface_options.designs_stats_view'),
    }


# Every command kind, in the docs' order.
COMMAND_KINDS = (
    'set_orders',
    'order_tagged',
    'create_fleet',
    'join_fleet',
    'leave_fleet',
    'disband_fleet',
    'set_fleet_options',
    'set_fleet_leader',
    'set_vehicle_strategy',
    'rename',
    'scrap',
    'mothball',
    'analyze',
    'self_destruct',
    'fire_on',
    'retrofit',
    'set_minister',
    'enter_sector',
    'open_vehicle_report',
    'queue_add',
    'queue_remove',
    'queue_move',
    'queue_set_count',
    'queue_flags',
    'queue_replace_facility',
    'set_colony_type',
    'abandon_planet',
    'cloak_colony',
    'transfer_cargo',
    'jettison_cargo',
    'create_design',
    'edit_design',
    'set_design_obsolete',
    'delete_design',
    'set_research',
    'set_intel',
    'send_message',
    'answer_message',
    'decide_war',
    'carry_out_demand',
    'use_demand_entry',
    'set_waypoint',
    'set_system_flags',
    'set_system_note',
    'tag_minefield',
    'set_strategy',
    'set_repair_priorities',
    'set_design_types',
    'set_colony_types',
    'set_empire_options',
    'set_email',
    'set_ministers',
    'set_encounter_options',
    'set_interface_options',
)

# The types above, by name.
TYPES = (
    'square',
    'location',
    'sector',
    'resources',
    'queue_target',
    'queue_item',
    'design',
    'design_entry',
    'research_project',
    'intel_project_order',
    'message',
    'package_item',
    'waypoint',
    'strategy',
    'strategy_setting',
    'population_group',
    'unit_stack',
    'interface_options',
)

# The orders, the tactical orders, and helpers written by hand (opense4/_cmd_extra.py).
from . import order, tactical  # noqa: E402
from ._cmd_extra import build, centre, give, only, without  # noqa: E402
