"""A constructor for every order kind (docs/sdk/commands.md, "Orders"): the orders of
set_orders and order_tagged. Each takes the fields its kind uses, and builds the order's map
with every field

Generated by tools/gen_sdk_python.py from docs/sdk/commands.md. Do not edit.
"""
from __future__ import annotations

from typing import Any, Dict, List, Optional, Sequence

from . import enums
from ._values import (LocationLike, Ref, ResourcesLike, TargetLike, _bool, _enum, _enums, _id, _ids, _index,
                      _indices, _int, _int_or_text, _list_of_int, _list_of_text, _orders, _piece, _ref,
                      _stellar, _struct, _structs, _text)


def move_to(location: Optional[LocationLike] = None) -> Dict[str, Any]:
    """Move to the sector.

    location: Where: a sector (Move To, Seek, a stellar manipulation's target).
    """
    return {
        'kind': 'move_to',
        'location': {'system': None, 'x': 6, 'y': 6} if location is None else _struct(location, 'location', 'move_to.location'),
        'object': None,
        'vehicle': None,
        'design': None,
        'amount': 0,
        'from_resource': 'minerals',
        'to_resource': 'minerals',
    }


def warp(object: Optional[Ref] = None) -> Dict[str, Any]:
    """Go through the warp point.

    object: A stellar object: a warp point, a planet, a manipulation's target.
    """
    return {
        'kind': 'warp',
        'location': {'system': None, 'x': 6, 'y': 6},
        'object': _ref(object, 'object', 'warp.object'),
        'vehicle': None,
        'design': None,
        'amount': 0,
        'from_resource': 'minerals',
        'to_resource': 'minerals',
    }


def attack(vehicle: Optional[Ref] = None, object: Optional[Ref] = None, location: Optional[LocationLike] = None) -> Dict[str, Any]:
    """Attack a vehicle, or a planet (object), where it was seen.

    vehicle: A vehicle: an attack's target, a pursuit, the unit group to recover from.
    object: A stellar object: a warp point, a planet, a manipulation's target.
    location: Where: a sector (Move To, Seek, a stellar manipulation's target).
    """
    return {
        'kind': 'attack',
        'location': {'system': None, 'x': 6, 'y': 6} if location is None else _struct(location, 'location', 'attack.location'),
        'object': _ref(object, 'object', 'attack.object'),
        'vehicle': _ref(vehicle, 'vehicle', 'attack.vehicle'),
        'design': None,
        'amount': 0,
        'from_resource': 'minerals',
        'to_resource': 'minerals',
    }


def resupply() -> Dict[str, Any]:
    """Go to the nearest place that resupplies us."""
    return {
        'kind': 'resupply',
        'location': {'system': None, 'x': 6, 'y': 6},
        'object': None,
        'vehicle': None,
        'design': None,
        'amount': 0,
        'from_resource': 'minerals',
        'to_resource': 'minerals',
    }


def repair() -> Dict[str, Any]:
    """Go to the nearest place that repairs us."""
    return {
        'kind': 'repair',
        'location': {'system': None, 'x': 6, 'y': 6},
        'object': None,
        'vehicle': None,
        'design': None,
        'amount': 0,
        'from_resource': 'minerals',
        'to_resource': 'minerals',
    }


def explore() -> Dict[str, Any]:
    """Explore the nearest system we have not explored."""
    return {
        'kind': 'explore',
        'location': {'system': None, 'x': 6, 'y': 6},
        'object': None,
        'vehicle': None,
        'design': None,
        'amount': 0,
        'from_resource': 'minerals',
        'to_resource': 'minerals',
    }


def colonize(object: Optional[Ref] = None, amount: int = 0) -> Dict[str, Any]:
    """Colonize the planet.

    object: A stellar object: a warp point, a planet, a manipulation's target.
    amount: A number whose meaning depends on the kind (see below).
    """
    return {
        'kind': 'colonize',
        'location': {'system': None, 'x': 6, 'y': 6},
        'object': _ref(object, 'object', 'colonize.object'),
        'vehicle': None,
        'design': None,
        'amount': _int(amount, 'colonize.amount'),
        'from_resource': 'minerals',
        'to_resource': 'minerals',
    }


def sentry() -> Dict[str, Any]:
    """Wait, ready to fight."""
    return {
        'kind': 'sentry',
        'location': {'system': None, 'x': 6, 'y': 6},
        'object': None,
        'vehicle': None,
        'design': None,
        'amount': 0,
        'from_resource': 'minerals',
        'to_resource': 'minerals',
    }


def load_cargo(design: Optional[Ref] = None, amount: int = 0) -> Dict[str, Any]:
    """Load units of the design, or population (no design); amount -1 is as much as fits.

    design: A design: the units to load, launch or recover, a retrofit's design.
    amount: A number whose meaning depends on the kind (see below).
    """
    return {
        'kind': 'load_cargo',
        'location': {'system': None, 'x': 6, 'y': 6},
        'object': None,
        'vehicle': None,
        'design': _ref(design, 'design', 'load_cargo.design'),
        'amount': _int(amount, 'load_cargo.amount'),
        'from_resource': 'minerals',
        'to_resource': 'minerals',
    }


def drop_cargo(design: Optional[Ref] = None, amount: int = 0) -> Dict[str, Any]:
    """Drop units or population, as for loading.

    design: A design: the units to load, launch or recover, a retrofit's design.
    amount: A number whose meaning depends on the kind (see below).
    """
    return {
        'kind': 'drop_cargo',
        'location': {'system': None, 'x': 6, 'y': 6},
        'object': None,
        'vehicle': None,
        'design': _ref(design, 'design', 'drop_cargo.design'),
        'amount': _int(amount, 'drop_cargo.amount'),
        'from_resource': 'minerals',
        'to_resource': 'minerals',
    }


def launch_units(design: Optional[Ref] = None, amount: int = 0) -> Dict[str, Any]:
    """Launch units of the design from cargo.

    design: A design: the units to load, launch or recover, a retrofit's design.
    amount: A number whose meaning depends on the kind (see below).
    """
    return {
        'kind': 'launch_units',
        'location': {'system': None, 'x': 6, 'y': 6},
        'object': None,
        'vehicle': None,
        'design': _ref(design, 'design', 'launch_units.design'),
        'amount': _int(amount, 'launch_units.amount'),
        'from_resource': 'minerals',
        'to_resource': 'minerals',
    }


def recover_units(design: Optional[Ref] = None, vehicle: Optional[Ref] = None, amount: int = 0) -> Dict[str, Any]:
    """Take units back aboard: every group of the design's kind, or only design from the group vehicle,
    up to amount.

    design: A design: the units to load, launch or recover, a retrofit's design.
    vehicle: A vehicle: an attack's target, a pursuit, the unit group to recover from.
    amount: A number whose meaning depends on the kind (see below).
    """
    return {
        'kind': 'recover_units',
        'location': {'system': None, 'x': 6, 'y': 6},
        'object': None,
        'vehicle': _ref(vehicle, 'vehicle', 'recover_units.vehicle'),
        'design': _ref(design, 'design', 'recover_units.design'),
        'amount': _int(amount, 'recover_units.amount'),
        'from_resource': 'minerals',
        'to_resource': 'minerals',
    }


def cloak() -> Dict[str, Any]:
    """Switch the cloak on."""
    return {
        'kind': 'cloak',
        'location': {'system': None, 'x': 6, 'y': 6},
        'object': None,
        'vehicle': None,
        'design': None,
        'amount': 0,
        'from_resource': 'minerals',
        'to_resource': 'minerals',
    }


def decloak() -> Dict[str, Any]:
    """Switch the cloak off."""
    return {
        'kind': 'decloak',
        'location': {'system': None, 'x': 6, 'y': 6},
        'object': None,
        'vehicle': None,
        'design': None,
        'amount': 0,
        'from_resource': 'minerals',
        'to_resource': 'minerals',
    }


def sweep_mines() -> Dict[str, Any]:
    """Sweep the mines in the sector."""
    return {
        'kind': 'sweep_mines',
        'location': {'system': None, 'x': 6, 'y': 6},
        'object': None,
        'vehicle': None,
        'design': None,
        'amount': 0,
        'from_resource': 'minerals',
        'to_resource': 'minerals',
    }


def use_component(amount: int = 0) -> Dict[str, Any]:
    """Use the component at position amount of the design.

    amount: A number whose meaning depends on the kind (see below).
    """
    return {
        'kind': 'use_component',
        'location': {'system': None, 'x': 6, 'y': 6},
        'object': None,
        'vehicle': None,
        'design': None,
        'amount': _int(amount, 'use_component.amount'),
        'from_resource': 'minerals',
        'to_resource': 'minerals',
    }


def stellar_manipulation(amount: int = 0, object: Optional[Ref] = None, location: Optional[LocationLike] = None) -> Dict[str, Any]:
    """The manipulation numbered amount in stellar_action, on a target.

    amount: A number whose meaning depends on the kind (see below).
    object: A stellar object: a warp point, a planet, a manipulation's target.
    location: Where: a sector (Move To, Seek, a stellar manipulation's target).
    """
    return {
        'kind': 'stellar_manipulation',
        'location': {'system': None, 'x': 6, 'y': 6} if location is None else _struct(location, 'location', 'stellar_manipulation.location'),
        'object': _ref(object, 'object', 'stellar_manipulation.object'),
        'vehicle': None,
        'design': None,
        'amount': _stellar(amount, 'stellar_manipulation.amount'),
        'from_resource': 'minerals',
        'to_resource': 'minerals',
    }


def move_to_waypoint(amount: int = 0) -> Dict[str, Any]:
    """Move to the waypoint in slot amount.

    amount: A number whose meaning depends on the kind (see below).
    """
    return {
        'kind': 'move_to_waypoint',
        'location': {'system': None, 'x': 6, 'y': 6},
        'object': None,
        'vehicle': None,
        'design': None,
        'amount': _int(amount, 'move_to_waypoint.amount'),
        'from_resource': 'minerals',
        'to_resource': 'minerals',
    }


def self_destruct() -> Dict[str, Any]:
    """Destroy the whole vehicle or group."""
    return {
        'kind': 'self_destruct',
        'location': {'system': None, 'x': 6, 'y': 6},
        'object': None,
        'vehicle': None,
        'design': None,
        'amount': 0,
        'from_resource': 'minerals',
        'to_resource': 'minerals',
    }


def use_facility(amount: int = 0) -> Dict[str, Any]:
    """A colony's: use the facility at position amount.

    amount: A number whose meaning depends on the kind (see below).
    """
    return {
        'kind': 'use_facility',
        'location': {'system': None, 'x': 6, 'y': 6},
        'object': None,
        'vehicle': None,
        'design': None,
        'amount': _int(amount, 'use_facility.amount'),
        'from_resource': 'minerals',
        'to_resource': 'minerals',
    }


def convert_resources(amount: int = 0, from_resource: str = 'minerals', to_resource: str = 'minerals') -> Dict[str, Any]:
    """A colony's: convert amount (at most 65,000) of one resource into another.

    amount: A number whose meaning depends on the kind (see below).
    from_resource: Convert Resources: the resource converted.
    to_resource: Convert Resources: the resource it becomes.
    """
    return {
        'kind': 'convert_resources',
        'location': {'system': None, 'x': 6, 'y': 6},
        'object': None,
        'vehicle': None,
        'design': None,
        'amount': _int(amount, 'convert_resources.amount'),
        'from_resource': _enum(from_resource, enums.RESOURCE, 'convert_resources.from_resource'),
        'to_resource': _enum(to_resource, enums.RESOURCE, 'convert_resources.to_resource'),
    }


def scrap() -> Dict[str, Any]:
    """Scrap the vehicle (the Scrap window's command)."""
    return {
        'kind': 'scrap',
        'location': {'system': None, 'x': 6, 'y': 6},
        'object': None,
        'vehicle': None,
        'design': None,
        'amount': 0,
        'from_resource': 'minerals',
        'to_resource': 'minerals',
    }


def analyze() -> Dict[str, Any]:
    """Take the vehicle apart to learn from it."""
    return {
        'kind': 'analyze',
        'location': {'system': None, 'x': 6, 'y': 6},
        'object': None,
        'vehicle': None,
        'design': None,
        'amount': 0,
        'from_resource': 'minerals',
        'to_resource': 'minerals',
    }


def mothball() -> Dict[str, Any]:
    """Mothball the vehicle."""
    return {
        'kind': 'mothball',
        'location': {'system': None, 'x': 6, 'y': 6},
        'object': None,
        'vehicle': None,
        'design': None,
        'amount': 0,
        'from_resource': 'minerals',
        'to_resource': 'minerals',
    }


def unmothball() -> Dict[str, Any]:
    """Bring it back into service."""
    return {
        'kind': 'unmothball',
        'location': {'system': None, 'x': 6, 'y': 6},
        'object': None,
        'vehicle': None,
        'design': None,
        'amount': 0,
        'from_resource': 'minerals',
        'to_resource': 'minerals',
    }


def retrofit(design: Optional[Ref] = None) -> Dict[str, Any]:
    """Refit to the design.

    design: A design: the units to load, launch or recover, a retrofit's design.
    """
    return {
        'kind': 'retrofit',
        'location': {'system': None, 'x': 6, 'y': 6},
        'object': None,
        'vehicle': None,
        'design': _ref(design, 'design', 'retrofit.design'),
        'amount': 0,
        'from_resource': 'minerals',
        'to_resource': 'minerals',
    }


def fire_on() -> Dict[str, Any]:
    """Our armed ships destroy this vehicle."""
    return {
        'kind': 'fire_on',
        'location': {'system': None, 'x': 6, 'y': 6},
        'object': None,
        'vehicle': None,
        'design': None,
        'amount': 0,
        'from_resource': 'minerals',
        'to_resource': 'minerals',
    }


def seek(location: Optional[LocationLike] = None, vehicle: Optional[Ref] = None, object: Optional[Ref] = None) -> Dict[str, Any]:
    """The computer's ministers' order: head for a sector, follow a vehicle or a planet, for one
    movement phase.

    location: Where: a sector (Move To, Seek, a stellar manipulation's target).
    vehicle: A vehicle: an attack's target, a pursuit, the unit group to recover from.
    object: A stellar object: a warp point, a planet, a manipulation's target.
    """
    return {
        'kind': 'seek',
        'location': {'system': None, 'x': 6, 'y': 6} if location is None else _struct(location, 'location', 'seek.location'),
        'object': _ref(object, 'object', 'seek.object'),
        'vehicle': _ref(vehicle, 'vehicle', 'seek.vehicle'),
        'design': None,
        'amount': 0,
        'from_resource': 'minerals',
        'to_resource': 'minerals',
    }


def join_fleet(amount: int = 0) -> Dict[str, Any]:
    """The ministers' order: follow the fleet whose id is amount and join it.

    amount: A number whose meaning depends on the kind (see below).
    """
    return {
        'kind': 'join_fleet',
        'location': {'system': None, 'x': 6, 'y': 6},
        'object': None,
        'vehicle': None,
        'design': None,
        'amount': _int(amount, 'join_fleet.amount'),
        'from_resource': 'minerals',
        'to_resource': 'minerals',
    }


# Every kind, in the docs' order.
KINDS = (
    'move_to',
    'warp',
    'attack',
    'resupply',
    'repair',
    'explore',
    'colonize',
    'sentry',
    'load_cargo',
    'drop_cargo',
    'launch_units',
    'recover_units',
    'cloak',
    'decloak',
    'sweep_mines',
    'use_component',
    'stellar_manipulation',
    'move_to_waypoint',
    'self_destruct',
    'use_facility',
    'convert_resources',
    'scrap',
    'analyze',
    'mothball',
    'unmothball',
    'retrofit',
    'fire_on',
    'seek',
    'join_fleet',
)
