"""A constructor for every tactical order kind (docs/sdk/commands.md, "Tactical battles"),
the answer to battle_round. Each takes the fields its kind uses (and the side giving it,
which opense4.ai fills in), and builds the order's map with every field

Generated by tools/gen_sdk_python.py from docs/sdk/commands.md. Do not edit.
"""
from __future__ import annotations

from typing import Any, Dict, List, Optional, Sequence, Union

from . import enums
from ._values import (LocationLike, Ref, ResourcesLike, TargetLike, _bool, _enum, _enums, _id, _ids, _index,
                      _indices, _int, _int_or_text, _list_of_int, _list_of_text, _orders, _piece, _ref,
                      _map, _stellar, _struct, _structs, _text)


def move(piece: Ref = -1, x: int = -1, y: int = -1, path: Optional[Sequence[Dict[str, Any]]] = None, alone: bool = False, *, empire: Optional[Ref] = None) -> Dict[str, Any]:
    """Move toward a square, or along a path of neighbouring squares.

    piece: The piece acting (-1 by default: none).
    x: Where to move: the square's column (-1 by default).
    y: ... and row (-1 by default).
    path: Or the squares to move along.
    alone: A group leader moves without its group.
    empire: The side giving it: the empire whose phase it is.
    """
    return {
        'kind': 'move',
        'empire': _id(empire, 'empire', 'move.empire'),
        'piece': _piece(piece, 'move.piece'),
        'target': -1,
        'weapon': -1,
        'instance': -1,
        'x': _int(x, 'move.x'),
        'y': _int(y, 'move.y'),
        'path': [] if path is None else _structs(path, 'square', 'move.path'),
        'design': None,
        'count': 0,
        'group': 0,
        'formation': -1,
        'on': True,
        'alone': _bool(alone, 'move.alone'),
    }


def fire(piece: Ref = -1, target: Ref = -1, weapon: int = -1, instance: int = -1, *, empire: Optional[Ref] = None) -> Dict[str, Any]:
    """Fire at a piece.

    piece: The piece acting (-1 by default: none).
    target: The target piece (-1 by default: none).
    weapon: The piece's weapon; -1 (the default) for every enabled weapon.
    instance: Which unit of a stack fires; -1 (the default) for every ready one.
    empire: The side giving it: the empire whose phase it is.
    """
    return {
        'kind': 'fire',
        'empire': _id(empire, 'empire', 'fire.empire'),
        'piece': _piece(piece, 'fire.piece'),
        'target': _piece(target, 'fire.target'),
        'weapon': _int(weapon, 'fire.weapon'),
        'instance': _int(instance, 'fire.instance'),
        'x': -1,
        'y': -1,
        'path': [],
        'design': None,
        'count': 0,
        'group': 0,
        'formation': -1,
        'on': True,
        'alone': False,
    }


def toggle_weapon(piece: Ref = -1, weapon: int = -1, on: bool = True, *, empire: Optional[Ref] = None) -> Dict[str, Any]:
    """Switch a weapon (or all) on or off.

    piece: The piece acting (-1 by default: none).
    weapon: The piece's weapon; -1 (the default) for every enabled weapon.
    on: Weapons on or off; Auto on or off (true by default).
    empire: The side giving it: the empire whose phase it is.
    """
    return {
        'kind': 'toggle_weapon',
        'empire': _id(empire, 'empire', 'toggle_weapon.empire'),
        'piece': _piece(piece, 'toggle_weapon.piece'),
        'target': -1,
        'weapon': _int(weapon, 'toggle_weapon.weapon'),
        'instance': -1,
        'x': -1,
        'y': -1,
        'path': [],
        'design': None,
        'count': 0,
        'group': 0,
        'formation': -1,
        'on': _bool(on, 'toggle_weapon.on'),
        'alone': False,
    }


def launch(piece: Ref = -1, design: Optional[Ref] = None, count: int = 0, group: int = 0, *, empire: Optional[Ref] = None) -> Dict[str, Any]:
    """Launch units.

    piece: The piece acting (-1 by default: none).
    design: The units to launch.
    count: How many units to launch.
    group: A combat group (0 to 9), a launch session, or a fighter group size.
    empire: The side giving it: the empire whose phase it is.
    """
    return {
        'kind': 'launch',
        'empire': _id(empire, 'empire', 'launch.empire'),
        'piece': _piece(piece, 'launch.piece'),
        'target': -1,
        'weapon': -1,
        'instance': -1,
        'x': -1,
        'y': -1,
        'path': [],
        'design': _id(design, 'design', 'launch.design'),
        'count': _int(count, 'launch.count'),
        'group': _int(group, 'launch.group'),
        'formation': -1,
        'on': True,
        'alone': False,
    }


def launch_fighters(piece: Ref = -1, design: Optional[Ref] = None, count: int = 0, group: int = 0, *, empire: Optional[Ref] = None) -> Dict[str, Any]:
    """Launch fighters in groups of group (5 to 50).

    piece: The piece acting (-1 by default: none).
    design: The units to launch.
    count: How many units to launch.
    group: A combat group (0 to 9), a launch session, or a fighter group size.
    empire: The side giving it: the empire whose phase it is.
    """
    return {
        'kind': 'launch_fighters',
        'empire': _id(empire, 'empire', 'launch_fighters.empire'),
        'piece': _piece(piece, 'launch_fighters.piece'),
        'target': -1,
        'weapon': -1,
        'instance': -1,
        'x': -1,
        'y': -1,
        'path': [],
        'design': _id(design, 'design', 'launch_fighters.design'),
        'count': _int(count, 'launch_fighters.count'),
        'group': _int(group, 'launch_fighters.group'),
        'formation': -1,
        'on': True,
        'alone': False,
    }


def drop_troops(piece: Ref = -1, *, empire: Optional[Ref] = None) -> Dict[str, Any]:
    """Land troops on the neighbouring enemy colony.

    piece: The piece acting (-1 by default: none).
    empire: The side giving it: the empire whose phase it is.
    """
    return {
        'kind': 'drop_troops',
        'empire': _id(empire, 'empire', 'drop_troops.empire'),
        'piece': _piece(piece, 'drop_troops.piece'),
        'target': -1,
        'weapon': -1,
        'instance': -1,
        'x': -1,
        'y': -1,
        'path': [],
        'design': None,
        'count': 0,
        'group': 0,
        'formation': -1,
        'on': True,
        'alone': False,
    }


def ram(piece: Ref = -1, target: Ref = -1, *, empire: Optional[Ref] = None) -> Dict[str, Any]:
    """Ram a neighbouring piece.

    piece: The piece acting (-1 by default: none).
    target: The target piece (-1 by default: none).
    empire: The side giving it: the empire whose phase it is.
    """
    return {
        'kind': 'ram',
        'empire': _id(empire, 'empire', 'ram.empire'),
        'piece': _piece(piece, 'ram.piece'),
        'target': _piece(target, 'ram.target'),
        'weapon': -1,
        'instance': -1,
        'x': -1,
        'y': -1,
        'path': [],
        'design': None,
        'count': 0,
        'group': 0,
        'formation': -1,
        'on': True,
        'alone': False,
    }


def capture(piece: Ref = -1, target: Ref = -1, *, empire: Optional[Ref] = None) -> Dict[str, Any]:
    """Board a neighbouring ship.

    piece: The piece acting (-1 by default: none).
    target: The target piece (-1 by default: none).
    empire: The side giving it: the empire whose phase it is.
    """
    return {
        'kind': 'capture',
        'empire': _id(empire, 'empire', 'capture.empire'),
        'piece': _piece(piece, 'capture.piece'),
        'target': _piece(target, 'capture.target'),
        'weapon': -1,
        'instance': -1,
        'x': -1,
        'y': -1,
        'path': [],
        'design': None,
        'count': 0,
        'group': 0,
        'formation': -1,
        'on': True,
        'alone': False,
    }


def set_leader(piece: Ref = -1, group: int = 0, formation: int = -1, *, empire: Optional[Ref] = None) -> Dict[str, Any]:
    """Lead a combat group in a formation.

    piece: The piece acting (-1 by default: none).
    group: A combat group (0 to 9), a launch session, or a fighter group size.
    formation: The formation a group leader takes (a formation index; -1 by default: none).
    empire: The side giving it: the empire whose phase it is.
    """
    return {
        'kind': 'set_leader',
        'empire': _id(empire, 'empire', 'set_leader.empire'),
        'piece': _piece(piece, 'set_leader.piece'),
        'target': -1,
        'weapon': -1,
        'instance': -1,
        'x': -1,
        'y': -1,
        'path': [],
        'design': None,
        'count': 0,
        'group': _int(group, 'set_leader.group'),
        'formation': _int(formation, 'set_leader.formation'),
        'on': True,
        'alone': False,
    }


def set_member(piece: Ref = -1, group: int = 0, *, empire: Optional[Ref] = None) -> Dict[str, Any]:
    """Join a combat group, taking the next place in its formation.

    piece: The piece acting (-1 by default: none).
    group: A combat group (0 to 9), a launch session, or a fighter group size.
    empire: The side giving it: the empire whose phase it is.
    """
    return {
        'kind': 'set_member',
        'empire': _id(empire, 'empire', 'set_member.empire'),
        'piece': _piece(piece, 'set_member.piece'),
        'target': -1,
        'weapon': -1,
        'instance': -1,
        'x': -1,
        'y': -1,
        'path': [],
        'design': None,
        'count': 0,
        'group': _int(group, 'set_member.group'),
        'formation': -1,
        'on': True,
        'alone': False,
    }


def clear_group(piece: Ref = -1, *, empire: Optional[Ref] = None) -> Dict[str, Any]:
    """Leave its group.

    piece: The piece acting (-1 by default: none).
    empire: The side giving it: the empire whose phase it is.
    """
    return {
        'kind': 'clear_group',
        'empire': _id(empire, 'empire', 'clear_group.empire'),
        'piece': _piece(piece, 'clear_group.piece'),
        'target': -1,
        'weapon': -1,
        'instance': -1,
        'x': -1,
        'y': -1,
        'path': [],
        'design': None,
        'count': 0,
        'group': 0,
        'formation': -1,
        'on': True,
        'alone': False,
    }


def clear_all_groups(*, empire: Optional[Ref] = None) -> Dict[str, Any]:
    """Every piece of the side leaves its group.

    empire: The side giving it: the empire whose phase it is.
    """
    return {
        'kind': 'clear_all_groups',
        'empire': _id(empire, 'empire', 'clear_all_groups.empire'),
        'piece': -1,
        'target': -1,
        'weapon': -1,
        'instance': -1,
        'x': -1,
        'y': -1,
        'path': [],
        'design': None,
        'count': 0,
        'group': 0,
        'formation': -1,
        'on': True,
        'alone': False,
    }


def auto(piece: Ref = -1, on: bool = True, *, empire: Optional[Ref] = None) -> Dict[str, Any]:
    """The piece acts by its strategy now; with piece -1 the battle's Auto switch.

    piece: The piece acting (-1 by default: none).
    on: Weapons on or off; Auto on or off (true by default).
    empire: The side giving it: the empire whose phase it is.
    """
    return {
        'kind': 'auto',
        'empire': _id(empire, 'empire', 'auto.empire'),
        'piece': _piece(piece, 'auto.piece'),
        'target': -1,
        'weapon': -1,
        'instance': -1,
        'x': -1,
        'y': -1,
        'path': [],
        'design': None,
        'count': 0,
        'group': 0,
        'formation': -1,
        'on': _bool(on, 'auto.on'),
        'alone': False,
    }


def auto_phase(*, empire: Optional[Ref] = None) -> Dict[str, Any]:
    """The strategies play the rest of this phase.

    empire: The side giving it: the empire whose phase it is.
    """
    return {
        'kind': 'auto_phase',
        'empire': _id(empire, 'empire', 'auto_phase.empire'),
        'piece': -1,
        'target': -1,
        'weapon': -1,
        'instance': -1,
        'x': -1,
        'y': -1,
        'path': [],
        'design': None,
        'count': 0,
        'group': 0,
        'formation': -1,
        'on': True,
        'alone': False,
    }


def end_phase(*, empire: Optional[Ref] = None) -> Dict[str, Any]:
    """End the side's phase.

    empire: The side giving it: the empire whose phase it is.
    """
    return {
        'kind': 'end_phase',
        'empire': _id(empire, 'empire', 'end_phase.empire'),
        'piece': -1,
        'target': -1,
        'weapon': -1,
        'instance': -1,
        'x': -1,
        'y': -1,
        'path': [],
        'design': None,
        'count': 0,
        'group': 0,
        'formation': -1,
        'on': True,
        'alone': False,
    }


def resolve_combat(*, empire: Optional[Ref] = None) -> Dict[str, Any]:
    """Every side follows its strategies to the end of the battle.

    empire: The side giving it: the empire whose phase it is.
    """
    return {
        'kind': 'resolve_combat',
        'empire': _id(empire, 'empire', 'resolve_combat.empire'),
        'piece': -1,
        'target': -1,
        'weapon': -1,
        'instance': -1,
        'x': -1,
        'y': -1,
        'path': [],
        'design': None,
        'count': 0,
        'group': 0,
        'formation': -1,
        'on': True,
        'alone': False,
    }


# Every kind, in the docs' order.
KINDS = (
    'move',
    'fire',
    'toggle_weapon',
    'launch',
    'launch_fighters',
    'drop_troops',
    'ram',
    'capture',
    'set_leader',
    'set_member',
    'clear_group',
    'clear_all_groups',
    'auto',
    'auto_phase',
    'end_phase',
    'resolve_combat',
)
