# Script mode (-P): writes a C++ source that builds files into the executable and
# defines opense4::embeddedResource() (src/core/embedded.hpp).
# Inputs: OUTPUT (the .cpp to write), ROOT (the source tree), FILES (paths relative
# to ROOT, separated by '|').

string(REPLACE "|" ";" files "${FILES}")

set(arrays "")
set(entries "")
set(index 0)
foreach(rel IN LISTS files)
    file(READ "${ROOT}/${rel}" hex HEX)
    string(LENGTH "${hex}" hex_len)
    math(EXPR size "${hex_len} / 2")
    # One "0xNN," per byte, 16 to a line.
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
    string(REGEX REPLACE "((0x[0-9a-f][0-9a-f],){16})" "\\1\n    " bytes "${bytes}")
    string(APPEND arrays "// ${rel}\nalignas(16) const unsigned char r${index}[] = {\n    ${bytes}\n};\n\n")
    string(APPEND entries "    {\"${rel}\", r${index}, ${size}},\n")
    math(EXPR index "${index} + 1")
endforeach()

file(WRITE "${OUTPUT}.tmp"
"// Generated by cmake/EmbedResources.cmake. Do not edit.\n"
"#include \"core/embedded.hpp\"\n\n"
"#include <cstddef>\n\n"
"namespace {\n\n"
"${arrays}"
"struct Entry {\n"
"    std::string_view path;\n"
"    const unsigned char* data;\n"
"    std::size_t size;\n"
"};\n\n"
"const Entry kEntries[] = {\n"
"${entries}"
"};\n\n"
"} // namespace\n\n"
"namespace opense4 {\n\n"
"std::span<const unsigned char> embeddedResource(std::string_view path) {\n"
"    for (const Entry& e : kEntries)\n"
"        if (e.path == path) return {e.data, e.size};\n"
"    return {};\n"
"}\n\n"
"} // namespace opense4\n")

# Only touch the output when its content changed, to avoid needless rebuilds.
file(COPY_FILE "${OUTPUT}.tmp" "${OUTPUT}" ONLY_IF_DIFFERENT)
file(REMOVE "${OUTPUT}.tmp")
