# Script mode (-P): writes a C++ source that builds Python files into the
# program: the script runtime's own modules (python/lib, defining
# opense4::script::libraryFiles(), src/script/runtime.hpp) or the SDK's
# `opense4` package (python/opense4, defining opense4::sdk::packageFiles(),
# src/sdk/players.hpp). Unlike the embedded resources these are always built
# in: the runtime and the computer players need them.
# Inputs: OUTPUT (the .cpp to write), ROOT (the folder of the files), FILES (paths
# relative to ROOT, separated by '|'; may be empty). Optional: HEADER (the
# header declaring the function), NAMESPACE, FUNCTION, ORIGIN (named in the
# generated file's first line).

if(NOT DEFINED HEADER)
    set(HEADER "script/runtime.hpp")
endif()
if(NOT DEFINED NAMESPACE)
    set(NAMESPACE "opense4::script")
endif()
if(NOT DEFINED FUNCTION)
    set(FUNCTION "libraryFiles")
endif()
if(NOT DEFINED ORIGIN)
    set(ORIGIN "python/lib")
endif()

string(REPLACE "|" ";" files "${FILES}")

set(arrays "")
set(entries "")
set(index 0)
foreach(rel IN LISTS files)
    if(rel STREQUAL "")
        continue()
    endif()
    file(READ "${ROOT}/${rel}" hex HEX)
    string(LENGTH "${hex}" hex_len)
    math(EXPR size "${hex_len} / 2")
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
    string(REGEX REPLACE "((0x[0-9a-f][0-9a-f],){16})" "\\1\n    " bytes "${bytes}")
    string(APPEND arrays "// ${rel}\nconst unsigned char f${index}[] = {\n    ${bytes}\n    0x00\n};\n\n")
    string(APPEND entries "    {\"${rel}\", std::string_view(reinterpret_cast<const char*>(f${index}), ${size})},\n")
    math(EXPR index "${index} + 1")
endforeach()

if(index EQUAL 0)
    set(body "std::span<const opense4::script::LibraryFile> ${FUNCTION}() {\n    return {};\n}\n")
    set(table "")
else()
    set(body "std::span<const opense4::script::LibraryFile> ${FUNCTION}() {\n    return kFiles;\n}\n")
    set(table "${arrays}const opense4::script::LibraryFile kFiles[] = {\n${entries}};\n\n")
endif()

file(WRITE "${OUTPUT}.tmp"
"// Generated by cmake/EmbedPython.cmake from ${ORIGIN}. Do not edit.\n"
"#include \"${HEADER}\"\n\n"
"namespace {\n\n"
"${table}"
"} // namespace\n\n"
"namespace ${NAMESPACE} {\n\n"
"${body}\n"
"} // namespace ${NAMESPACE}\n")

file(COPY_FILE "${OUTPUT}.tmp" "${OUTPUT}" ONLY_IF_DIFFERENT)
file(REMOVE "${OUTPUT}.tmp")
