# Script mode (-P): writes a header embedding a SPIR-V binary and a GLSL source.
# Inputs: OUTPUT, IDENT, SPIRV, SOURCE

function(_opense4_hex_bytes path out_var)
    file(READ "${path}" hex HEX)
    string(LENGTH "${hex}" hex_len)
    math(EXPR byte_count "${hex_len} / 2")
    # One "0xNN," per byte, wrapped every 16 bytes.
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
    string(REGEX REPLACE "((0x[0-9a-f][0-9a-f],){16})" "\\1\n    " bytes "${bytes}")
    set(${out_var} "${bytes}" PARENT_SCOPE)
    set(${out_var}_size "${byte_count}" PARENT_SCOPE)
endfunction()

_opense4_hex_bytes("${SPIRV}" spirv)
_opense4_hex_bytes("${SOURCE}" glsl)

file(WRITE "${OUTPUT}.tmp"
"// Generated by cmake/EmbedFiles.cmake. Do not edit.\n"
"#pragma once\n"
"#include <cstddef>\n\n"
"namespace opense4::shaders {\n"
"alignas(4) inline constexpr unsigned char ${IDENT}_spirv[] = {\n    ${spirv}\n};\n"
"inline constexpr std::size_t ${IDENT}_spirv_size = ${spirv_size};\n"
"inline constexpr char ${IDENT}_glsl[] = {\n    ${glsl}\n    0x00\n};\n"
"} // namespace opense4::shaders\n")

# Only touch the output when content changed, to avoid needless rebuilds.
file(COPY_FILE "${OUTPUT}.tmp" "${OUTPUT}" ONLY_IF_DIFFERENT)
file(REMOVE "${OUTPUT}.tmp")
