# Script mode (-P): writes a C++ source that builds the script runtime's own Python
# modules (python/lib) into the program and defines opense4::script::libraryFiles()
# (src/script/runtime.hpp). Unlike the embedded resources these are always built
# in: the runtime needs them.
# Inputs: OUTPUT (the .cpp to write), ROOT (the folder of the files), FILES (paths
# relative to ROOT, separated by '|').

string(REPLACE "|" ";" files "${FILES}")

set(arrays "")
set(entries "")
set(index 0)
foreach(rel IN LISTS files)
    file(READ "${ROOT}/${rel}" hex HEX)
    string(LENGTH "${hex}" hex_len)
    math(EXPR size "${hex_len} / 2")
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
    string(REGEX REPLACE "((0x[0-9a-f][0-9a-f],){16})" "\\1\n    " bytes "${bytes}")
    string(APPEND arrays "// ${rel}\nconst unsigned char f${index}[] = {\n    ${bytes}\n    0x00\n};\n\n")
    string(APPEND entries "    {\"${rel}\", std::string_view(reinterpret_cast<const char*>(f${index}), ${size})},\n")
    math(EXPR index "${index} + 1")
endforeach()

file(WRITE "${OUTPUT}.tmp"
"// Generated by cmake/EmbedPython.cmake from python/lib. Do not edit.\n"
"#include \"script/runtime.hpp\"\n\n"
"namespace {\n\n"
"${arrays}"
"const opense4::script::LibraryFile kFiles[] = {\n"
"${entries}"
"};\n\n"
"} // namespace\n\n"
"namespace opense4::script {\n\n"
"std::span<const LibraryFile> libraryFiles() {\n"
"    return kFiles;\n"
"}\n\n"
"} // namespace opense4::script\n")

file(COPY_FILE "${OUTPUT}.tmp" "${OUTPUT}" ONLY_IF_DIFFERENT)
file(REMOVE "${OUTPUT}.tmp")
